package com.submeet.client.autore.view;

import com.submeet.client.account.controller.HomeControl;
import com.submeet.client.autore.controller.AuthorConferenceControl;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import java.awt.event.ActionListener;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.util.List;
import java.util.Map;

public class AvailableConferenceView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AvailableConferenceView.class.getName());
    private HomeControl homeControl;
    private AuthorConferenceControl authorConferenceControl;
    private List<Map<String, Object>> conferenceList;


    /**
     * Creates new form AvaibleConferenceView
     */
    public AvailableConferenceView(HomeControl homeControl, AuthorConferenceControl authorConferenceControl, List<Map<String, Object>> conferenceList) {
        this.homeControl = homeControl;
        this.conferenceList = conferenceList;
        this.authorConferenceControl = authorConferenceControl;

        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        displayConferenceList();
        // Imposta dimensioni percentuali iniziali
        adjustColumnWidths();
        // Riallinea le percentuali ad ogni resize della tabella
        scrollPanelConferences.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                adjustColumnWidths();
            }
        });

        setVisible(true);
    }

    private void adjustColumnWidths() {
        // Disabilita l'auto‐resize
        tableConferences.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);
        // Larghezza disponibile nel viewport
        int totalWidth = scrollPanelConferences.getViewport().getWidth();
        TableColumnModel colModel = tableConferences.getColumnModel();
        // Colonna CODICE = 30%
        colModel.getColumn(0).setPreferredWidth((int)(totalWidth * 0.15));
        // Colonna NOME = 70%
        colModel.getColumn(1).setPreferredWidth((int)(totalWidth * 0.85));
    }

    // Display conference list
    private void displayConferenceList() {
        DefaultTableModel model = (DefaultTableModel) tableConferences.getModel();
        model.setRowCount(0); // Clear the table

        if (conferenceList != null && !conferenceList.isEmpty()) {
            for (Map<String, Object> conference : conferenceList) {
                model.addRow(new Object[]{
                        conference.get("conferenceId"),
                        conference.get("title")
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelCMS = new javax.swing.JLabel();
        panelBarra = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        availableConferenceButton = new javax.swing.JButton();
        participationConferenceButton = new javax.swing.JButton();
        scrollPanelConferences = new javax.swing.JScrollPane();
        tableConferences = new javax.swing.JTable();
        labelText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SubMeet_140x140.png"))); // NOI18N

        labelCMS.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelCMS.setForeground(new java.awt.Color(36, 105, 186));
        labelCMS.setText("CONFERENCE MANAGEMENT SYSTEM");

        panelBarra.setBackground(new java.awt.Color(204, 204, 204));
        panelBarra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBarra.setPreferredSize(new java.awt.Dimension(233, 23));

        homeButton.setBackground(new java.awt.Color(204, 204, 204));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-home-16.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.setPreferredSize(new java.awt.Dimension(20, 20));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        availableConferenceButton.setBackground(new java.awt.Color(153, 153, 255));
        availableConferenceButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        availableConferenceButton.setText("CONFERENZE DISPONIBILI");
        availableConferenceButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        participationConferenceButton.setBackground(new java.awt.Color(153, 153, 255));
        participationConferenceButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        participationConferenceButton.setText("PARTECIPAZIONI");
        participationConferenceButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        participationConferenceButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participationConferenceButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBarraLayout = new javax.swing.GroupLayout(panelBarra);
        panelBarra.setLayout(panelBarraLayout);
        panelBarraLayout.setHorizontalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBarraLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(availableConferenceButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(participationConferenceButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
        );
        panelBarraLayout.setVerticalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(availableConferenceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(participationConferenceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(3, 3, 3))
        );

        scrollPanelConferences.setBackground(new java.awt.Color(255, 255, 255));
        scrollPanelConferences.setBorder(null);
        scrollPanelConferences.setToolTipText("");

        tableConferences.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                },
                new String [] {
                        "CODICE", "NOME CONFERENZA"
                }
        ) {
            Class[] types = new Class [] {
                    java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                    false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableConferences.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableConferences.setGridColor(new java.awt.Color(102, 102, 255));
        tableConferences.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableConferencesMouseClicked(evt);
            }
        });
        scrollPanelConferences.setViewportView(tableConferences);

        labelText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        labelText.setText("CONFERENZE DISPONIBILI");

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBarra, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(labelCMS))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(scrollPanelConferences, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(labelText))))
                                .addContainerGap(60, Short.MAX_VALUE))
        );
        panelBackgroundLayout.setVerticalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(labelCMS)))
                                .addGap(18, 18, 18)
                                .addComponent(panelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(labelText)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(scrollPanelConferences, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(73, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    public void setConferencePartecipationButton(ActionListener listener) {
        participationConferenceButton.addActionListener(listener);
    }

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        homeControl.createHomeRouterView();
        this.dispose();
    }

    private void participationConferenceButtonActionPerformed(java.awt.event.ActionEvent evt) {

    }

    private void tableConferencesMouseClicked(java.awt.event.MouseEvent evt) {
        // Get the selected row
        int row = tableConferences.getSelectedRow();
        if (row >= 0) {
            // Get the conference ID from the first column
            int conferenceId = (int) tableConferences.getValueAt(row, 0);
            // Show conference info
            authorConferenceControl.showConferenceInfo(conferenceId);
            // Close this window
            this.dispose();
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JButton availableConferenceButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel labelCMS;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelText;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelBarra;
    private javax.swing.JButton participationConferenceButton;
    private javax.swing.JScrollPane scrollPanelConferences;
    private javax.swing.JTable tableConferences;
    // End of variables declaration
}
