package com.submeet.client.autore.view;

import com.submeet.client.account.controller.HomeControl;
import com.submeet.client.autore.controller.AuthorConferenceControl;
import com.submeet.client.entity.EntityConference;
import com.submeet.client.utility.AppSession;
import com.submeet.dbmsboundary.DBMSBoundary;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import java.util.Map;

public class NewConferenceInfoView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NewConferenceInfoView.class.getName());
    private HomeControl homeControl;
    private AuthorConferenceControl authorConferenceControl;
    private EntityConference conference;

    /**
     * Creates new form ConferenceInfoView
     */
    public NewConferenceInfoView() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * Creates new form ConferenceInfoView with conference information
     */
    public NewConferenceInfoView(HomeControl homeControl, AuthorConferenceControl authorConferenceControl, EntityConference conference) {
        this.homeControl = homeControl;
        this.authorConferenceControl = authorConferenceControl;
        this.conference = conference;

        initComponents();
        setLocationRelativeTo(null);

        // Set conference information in the UI
        labelSetConferenceName.setText(conference.getTitle());
        labelSetInterestAreas.setText(String.join(", ", conference.getSpecializations()));
        labelSetConferenceDate.setText(conference.getScheduleDate().toString());
        labelSetSubmissionExpirationDate.setText(conference.getSubmissionDeadline().toString());
        labelSetReviewExpirationDate.setText(conference.getReviewDeadline().toString());
        labelSetFinalVersionExpirationDate.setText(conference.getFinalVersionDeadline().toString());
        labelSetLanguages.setText(String.join(", ", conference.getLanguages()));
        labelSetMaxReviewer.setText(String.valueOf(conference.getReviewerForPaper()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelCMS = new javax.swing.JLabel();
        panelBarra = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        panelTitle = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        panelFields = new javax.swing.JPanel();
        labelConferenceName = new javax.swing.JLabel();
        labelSetConferenceName = new javax.swing.JLabel();
        labelInterestAreas = new javax.swing.JLabel();
        labelSetInterestAreas = new javax.swing.JLabel();
        labelSubmissionExpirationDate = new javax.swing.JLabel();
        labelReviewExpirationDate = new javax.swing.JLabel();
        labelFialVersionExpirationDate = new javax.swing.JLabel();
        labelLanguages = new javax.swing.JLabel();
        labelMaxReviewer = new javax.swing.JLabel();
        labelSetSubmissionExpirationDate = new javax.swing.JLabel();
        labelSetReviewExpirationDate = new javax.swing.JLabel();
        labelSetFinalVersionExpirationDate = new javax.swing.JLabel();
        labelSetLanguages = new javax.swing.JLabel();
        labelSetMaxReviewer = new javax.swing.JLabel();
        labelConferenceDate = new javax.swing.JLabel();
        labelSetConferenceDate = new javax.swing.JLabel();
        partecipateButton = new javax.swing.JButton();
        checkBox = new javax.swing.JCheckBox();
        labelPolicy = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SubMeet_140x140.png"))); // NOI18N

        labelCMS.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelCMS.setForeground(new java.awt.Color(36, 105, 186));
        labelCMS.setText("CONFERENCE MANAGEMENT SYSTEM");

        panelBarra.setBackground(new java.awt.Color(204, 204, 204));
        panelBarra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBarra.setPreferredSize(new java.awt.Dimension(233, 23));

        homeButton.setBackground(new java.awt.Color(204, 204, 204));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-home-16.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.setPreferredSize(new java.awt.Dimension(20, 20));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(204, 204, 204));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-back-20.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        panelTitle.setBackground(new java.awt.Color(153, 153, 255));
        panelTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelTitle.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("INFORMAZIONI");

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
                panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTitleLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        panelTitleLayout.setVerticalGroup(
                panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelTitle))
        );

        javax.swing.GroupLayout panelBarraLayout = new javax.swing.GroupLayout(panelBarra);
        panelBarra.setLayout(panelBarraLayout);
        panelBarraLayout.setHorizontalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBarraLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
        );
        panelBarraLayout.setVerticalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(backButton)
                                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelFields.setBackground(new java.awt.Color(153, 153, 255));

        labelConferenceName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelConferenceName.setText("Nome Conferenza:");

        labelSetConferenceName.setText("aaaaaaaaaaaaaaaaaaaaaa");
        labelSetConferenceName.setMaximumSize(new java.awt.Dimension(380, 16));

        labelInterestAreas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInterestAreas.setText("Aree Specialistiche");

        labelSetInterestAreas.setText("aaaaaaaaaaaaaaaa");
        labelSetInterestAreas.setMaximumSize(new java.awt.Dimension(380, 16));

        labelSubmissionExpirationDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelSubmissionExpirationDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubmissionExpirationDate.setText("Data Scadenza Sottomissioni:");

        labelReviewExpirationDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelReviewExpirationDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelReviewExpirationDate.setText("Data Scadenza Revisioni:");

        labelFialVersionExpirationDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelFialVersionExpirationDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFialVersionExpirationDate.setText("Data Scadenza Sottomissioni Versioni Finali:");

        labelLanguages.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelLanguages.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLanguages.setText("Lingue:");

        labelMaxReviewer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelMaxReviewer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMaxReviewer.setText("N° Revisori Per Articolo (MAX):");

        labelSetSubmissionExpirationDate.setText("a");
        labelSetSubmissionExpirationDate.setMaximumSize(new java.awt.Dimension(145, 16));

        labelSetReviewExpirationDate.setText("a");
        labelSetReviewExpirationDate.setMaximumSize(new java.awt.Dimension(145, 16));

        labelSetFinalVersionExpirationDate.setText("a");
        labelSetFinalVersionExpirationDate.setMaximumSize(new java.awt.Dimension(145, 16));

        labelSetLanguages.setText("a");
        labelSetLanguages.setMaximumSize(new java.awt.Dimension(145, 16));

        labelSetMaxReviewer.setText("a");

        labelConferenceDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelConferenceDate.setText("Data Conferenza:");

        labelSetConferenceDate.setText("a");

        javax.swing.GroupLayout panelFieldsLayout = new javax.swing.GroupLayout(panelFields);
        panelFields.setLayout(panelFieldsLayout);
        panelFieldsLayout.setHorizontalGroup(
                panelFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFieldsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelConferenceName)
                                        .addComponent(labelSetConferenceName, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelInterestAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelFieldsLayout.createSequentialGroup()
                                                .addComponent(labelMaxReviewer)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelSetMaxReviewer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelFieldsLayout.createSequentialGroup()
                                                .addComponent(labelLanguages)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelSetLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelFieldsLayout.createSequentialGroup()
                                                .addComponent(labelFialVersionExpirationDate)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelSetFinalVersionExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelFieldsLayout.createSequentialGroup()
                                                .addComponent(labelReviewExpirationDate)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelSetReviewExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelFieldsLayout.createSequentialGroup()
                                                .addComponent(labelSubmissionExpirationDate)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelSetSubmissionExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelFieldsLayout.createSequentialGroup()
                                                .addComponent(labelConferenceDate)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelSetConferenceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(labelSetInterestAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(44, Short.MAX_VALUE))
        );
        panelFieldsLayout.setVerticalGroup(
                panelFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFieldsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelConferenceName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSetConferenceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelInterestAreas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSetInterestAreas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelConferenceDate)
                                        .addComponent(labelSetConferenceDate))
                                .addGap(18, 18, 18)
                                .addGroup(panelFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelSubmissionExpirationDate)
                                        .addComponent(labelSetSubmissionExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelReviewExpirationDate)
                                        .addComponent(labelSetReviewExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelFialVersionExpirationDate)
                                        .addComponent(labelSetFinalVersionExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelLanguages)
                                        .addComponent(labelSetLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(panelFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelMaxReviewer)
                                        .addComponent(labelSetMaxReviewer))
                                .addContainerGap(20, Short.MAX_VALUE))
        );

        partecipateButton.setBackground(new java.awt.Color(153, 153, 255));
        partecipateButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        partecipateButton.setText("PARTECIPA");
        partecipateButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        partecipateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                partecipateButtonActionPerformed(evt);
            }
        });

        checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxActionPerformed(evt);
            }
        });

        labelPolicy.setText("<html>\n  Dichiaro di aver preso visione e di accettare il regolamento della conferenza<br>\nl’informativa sulla privacy e le disposizioni relative al diritto d’autore.\n</html>\n");

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBarra, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(labelCMS))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(panelFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                                .addComponent(checkBox)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(labelPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(211, 211, 211)
                                                .addComponent(partecipateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(62, Short.MAX_VALUE))
        );
        panelBackgroundLayout.setVerticalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(labelCMS)))
                                .addGap(18, 18, 18)
                                .addComponent(panelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(panelFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(checkBox)
                                        .addComponent(labelPolicy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(partecipateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 21, Short.MAX_VALUE))
        );

        partecipateButton.setEnabled(false);
        checkBox.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if(checkBox.isSelected()){
                    partecipateButton.setEnabled(true);
                } else {
                    partecipateButton.setEnabled(false);
                }
            }
        });

        pack();
    }// </editor-fold>

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Navigate to home view
        homeControl.createHomeRouterView();
        this.dispose();
    }

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Navigate back to available conferences view using HomeControl's method
        homeControl.navigateToAuthorView(authorConferenceControl);
        this.dispose();
    }

    private void partecipateButtonActionPerformed(java.awt.event.ActionEvent evt) {
        authorConferenceControl.newPartecipation(AppSession.getInstance().getUserId(), conference.getConferenceId());
        this.dispose();
    }

    private void checkBoxActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    // Variables declaration - do not modify
    private javax.swing.JButton backButton;
    private javax.swing.JCheckBox checkBox;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel labelCMS;
    private javax.swing.JLabel labelConferenceDate;
    private javax.swing.JLabel labelConferenceName;
    private javax.swing.JLabel labelFialVersionExpirationDate;
    private javax.swing.JLabel labelInterestAreas;
    private javax.swing.JLabel labelLanguages;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelMaxReviewer;
    private javax.swing.JLabel labelPolicy;
    private javax.swing.JLabel labelReviewExpirationDate;
    private javax.swing.JLabel labelSetConferenceDate;
    private javax.swing.JLabel labelSetConferenceName;
    private javax.swing.JLabel labelSetFinalVersionExpirationDate;
    private javax.swing.JLabel labelSetInterestAreas;
    private javax.swing.JLabel labelSetLanguages;
    private javax.swing.JLabel labelSetMaxReviewer;
    private javax.swing.JLabel labelSetReviewExpirationDate;
    private javax.swing.JLabel labelSetSubmissionExpirationDate;
    private javax.swing.JLabel labelSubmissionExpirationDate;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelBarra;
    private javax.swing.JPanel panelFields;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JButton partecipateButton;
    // End of variables declaration
}
