package com.submeet.client.autore.view;

import com.submeet.client.account.controller.HomeControl;
import com.submeet.client.autore.controller.AuthorConferenceControl;
import com.submeet.client.common.ErrorPopupView;
import com.submeet.client.entity.EntityReview;

import javax.swing.*;
import java.io.File;
import java.util.List;
import java.util.Objects;

public class PaperInfoView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaperInfoView.class.getName());
    private HomeControl homeControl;
    private AuthorConferenceControl authorConferenceControl;
    private List<EntityReview> reviews;
    private int conferenceId;
    private String conferenceTitle;
    private int paperId;
    private String paperState;

    /**
     * Creates new form PaperDashboardView
     */
    public PaperInfoView(HomeControl homeControl, AuthorConferenceControl authorConferenceControl, List<EntityReview> reviews, int conferenceId, String conferenceTitle, int paperId, String paperState) {
        this.homeControl = homeControl;
        this.authorConferenceControl = authorConferenceControl;
        this.reviews = reviews;
        this.conferenceId = conferenceId;
        this.conferenceTitle = conferenceTitle;
        this.paperId = paperId;
        this.paperState = paperState;

        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);

        this.displayReview();
        submitFinalVersionButton.setVisible(false);
        if(paperState.equals("Revisionato")) {
            submitFinalVersionButton.setVisible(true);
        }
    }

    public void displayReview() {
        fieldPaperTitle.setText(conferenceTitle);
        fieldPaperTitle.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        submitFinalVersionButton.setVisible(false);
        retirePaperButton.setVisible(false);
        fieldReviewState.setText(paperState);

        panelReviews.setLayout(new BoxLayout(panelReviews, BoxLayout.Y_AXIS));
        panelReviews.removeAll();


        if(reviews.isEmpty()) {
            retirePaperButton.setVisible(true);
        } else {
            boolean isReviewDone = true;

            for (EntityReview review : reviews) {
                if (!Objects.equals(review.getState(), "done")) {
                    isReviewDone = false;
                    continue;
                }
                JTextArea reviewText = new JTextArea(review.getReviewComment());
                reviewText.setLineWrap(true);
                reviewText.setWrapStyleWord(true);
                reviewText.setEditable(false);
                reviewText.setBackground(panelReviews.getBackground());
                reviewText.setBorder(BorderFactory.createTitledBorder("Revisione"));
                reviewText.setPreferredSize(new java.awt.Dimension(panelReviews.getWidth(), 100));
                reviewText.setMinimumSize(new java.awt.Dimension(600, Integer.MAX_VALUE));
                reviewText.setMaximumSize(new java.awt.Dimension(600, Integer.MAX_VALUE));

                panelReviews.add(reviewText);
            }

            if(isReviewDone) {
                fieldReviewState.setDisabledTextColor(new java.awt.Color(0, 0, 0));
                submitFinalVersionButton.setVisible(true);
            } else {
                submitFinalVersionButton.setVisible(false);
            }
        }

        panelReviews.revalidate();
        panelReviews.repaint();
        scrollPanelReviews.setViewportView(panelReviews);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelCMS = new javax.swing.JLabel();
        panelBarra = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        panelTitle = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelPaperTitle = new javax.swing.JLabel();
        fieldPaperTitle = new javax.swing.JTextField();
        labelReviews = new javax.swing.JLabel();
        fieldReviewState = new javax.swing.JTextField();
        scrollPanelReviews = new javax.swing.JScrollPane();
        panelReviews = new javax.swing.JPanel();
        labelConference2 = new javax.swing.JLabel();
        retirePaperButton = new javax.swing.JButton();
        submitFinalVersionButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SubMeet_140x140.png"))); // NOI18N

        labelCMS.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelCMS.setForeground(new java.awt.Color(36, 105, 186));
        labelCMS.setText("CONFERENCE MANAGEMENT SYSTEM");

        panelBarra.setBackground(new java.awt.Color(204, 204, 204));
        panelBarra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBarra.setPreferredSize(new java.awt.Dimension(233, 23));

        homeButton.setBackground(new java.awt.Color(204, 204, 204));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-home-16.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.setPreferredSize(new java.awt.Dimension(20, 20));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(204, 204, 204));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-back-20.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        panelTitle.setBackground(new java.awt.Color(153, 153, 255));
        panelTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelTitle.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("VISUALIZZA PAPER");

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
                panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTitleLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(9, 9, 9))
        );
        panelTitleLayout.setVerticalGroup(
                panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelTitle))
        );

        javax.swing.GroupLayout panelBarraLayout = new javax.swing.GroupLayout(panelBarra);
        panelBarra.setLayout(panelBarraLayout);
        panelBarraLayout.setHorizontalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBarraLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
        );
        panelBarraLayout.setVerticalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(backButton)
                                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        labelPaperTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPaperTitle.setText("Titolo");

        fieldPaperTitle.setEditable(false);
        fieldPaperTitle.setMaximumSize(new java.awt.Dimension(64, 22));
        fieldPaperTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPaperTitleActionPerformed(evt);
            }
        });

        labelReviews.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelReviews.setText("Revisioni");

        fieldReviewState.setEditable(false);
        fieldReviewState.setEnabled(false);
        fieldReviewState.setMaximumSize(new java.awt.Dimension(64, 22));
        fieldReviewState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldReviewStateActionPerformed(evt);
            }
        });

        panelReviews.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout panelReviewsLayout = new javax.swing.GroupLayout(panelReviews);
        panelReviews.setLayout(panelReviewsLayout);
        panelReviewsLayout.setHorizontalGroup(
                panelReviewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 372, Short.MAX_VALUE)
        );
        panelReviewsLayout.setVerticalGroup(
                panelReviewsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 241, Short.MAX_VALUE)
        );

        scrollPanelReviews.setViewportView(panelReviews);

        labelConference2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelConference2.setText("Stato Revisione");

        retirePaperButton.setBackground(new java.awt.Color(153, 153, 255));
        retirePaperButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        retirePaperButton.setText("RITIRA PAPER");
        retirePaperButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        retirePaperButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirePaperButtonActionPerformed(evt);
            }
        });

        submitFinalVersionButton.setBackground(new java.awt.Color(153, 153, 255));
        submitFinalVersionButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitFinalVersionButton.setText("<html><center>SOTTOMETTI<br>VERSIONE FINALE</center></html>\n");
        submitFinalVersionButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        submitFinalVersionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitFinalVersionButtonActionPerformed(evt);
            }
        });
        submitFinalVersionButton.setVisible(false);

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBarra, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(labelCMS))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(labelConference2)
                                                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelBackgroundLayout.createSequentialGroup()
                                                                        .addComponent(retirePaperButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                        .addComponent(submitFinalVersionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addComponent(fieldReviewState, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(labelPaperTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(fieldPaperTitle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(labelReviews, javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addComponent(scrollPanelReviews, javax.swing.GroupLayout.Alignment.LEADING)))))
                                .addContainerGap(40, Short.MAX_VALUE))
        );
        panelBackgroundLayout.setVerticalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addComponent(labelCMS)))
                                .addGap(18, 18, 18)
                                .addComponent(panelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelPaperTitle)
                                .addGap(3, 3, 3)
                                .addComponent(fieldPaperTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(labelConference2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldReviewState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelReviews)
                                .addGap(4, 4, 4)
                                .addComponent(scrollPanelReviews, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(retirePaperButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(submitFinalVersionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        homeControl.returnToHome();
        this.dispose();
    }

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {
        authorConferenceControl.showPaperDashboardView(conferenceId, conferenceTitle);
        this.dispose();
    }

    private void fieldPaperTitleActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void fieldReviewStateActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void retirePaperButtonActionPerformed(java.awt.event.ActionEvent evt) {
        if(authorConferenceControl.retirePaper(paperId, conferenceId, conferenceTitle))
        {
            this.dispose();
        }
    }

    private void submitFinalVersionButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Create a file chooser
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleziona la versione finale del paper");

        // Set file filter to only show PDF files
        fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File f) {
                return f.isDirectory() || f.getName().toLowerCase().endsWith(".pdf");
            }

            @Override
            public String getDescription() {
                return "PDF Files (*.pdf)";
            }
        });

        // Show the dialog and get the result
        int result = fileChooser.showOpenDialog(this);

        // If a file was selected, submit the final version
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            // Controllo che il file non sia nullo o vuoto
            if (selectedFile == null || !selectedFile.exists()) {
                new ErrorPopupView("Errore nel caricamento del file.");
                return;
            }

            // Esegui la sottomissione della versione finale
            if(authorConferenceControl.submitFinalVersion(paperId, selectedFile))
            {
                this.dispose();
                authorConferenceControl.showPaperDashboardView(conferenceId, conferenceTitle);
            }
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JButton backButton;
    private javax.swing.JTextField fieldPaperTitle;
    private javax.swing.JTextField fieldReviewState;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel labelCMS;
    private javax.swing.JLabel labelConference2;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelPaperTitle;
    private javax.swing.JLabel labelReviews;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelBarra;
    private javax.swing.JPanel panelReviews;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JButton retirePaperButton;
    private javax.swing.JScrollPane scrollPanelReviews;
    private javax.swing.JButton submitFinalVersionButton;
    // End of variables declaration
}
