package com.submeet.client.autore.view;

import com.submeet.client.account.controller.HomeControl;
import com.submeet.client.autore.controller.AuthorConferenceControl;
import com.submeet.client.common.ErrorPopupView;
import com.submeet.client.entity.EntityConference;
import com.submeet.client.utility.AppSession;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.util.List;
import java.util.Map;

public class SubmitPaperView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SubmitPaperView.class.getName());

    private HomeControl homeControl;
    private AuthorConferenceControl authorConferenceControl;
    private EntityConference conference;
    private File selectedFile;

    /**
     * Creates new form SubmitPaperView
     */
    public SubmitPaperView(HomeControl homeControl, AuthorConferenceControl authorConferenceControl, EntityConference conference, List<Map<Integer, String>> specializations) {
        this.homeControl = homeControl;
        this.authorConferenceControl = authorConferenceControl;
        this.conference = conference;

        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        populatePanelInterestAreas(specializations);
    }

    /**
     * Populates the panel with interest areas (specializations) as checkboxes
     */
    public void populatePanelInterestAreas(List<Map<Integer, String>> interestAreas) {
        panelInterestAreas.setLayout(new BoxLayout(panelInterestAreas, BoxLayout.Y_AXIS));

        if (interestAreas != null) {
            for (Map<Integer, String> area : interestAreas) {
                for (Map.Entry<Integer, String> entry : area.entrySet()) {
                    int id = entry.getKey();
                    String name = entry.getValue();

                    // Create a checkbox with the specialization name
                    JCheckBox checkBox = new JCheckBox(name);
                    checkBox.setActionCommand(String.valueOf(id));

                    panelInterestAreas.add(checkBox);
                }
            }

            // Refresh the panel to display the new checkboxes
            panelInterestAreas.revalidate();
            panelInterestAreas.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelCMS = new javax.swing.JLabel();
        panelBarra = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        panelTitle = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        uploadPaperButton = new javax.swing.JButton();
        submitPaperButton = new javax.swing.JButton();
        labelPaperTitle = new javax.swing.JLabel();
        fieldPaperTitle = new javax.swing.JTextField();
        labelInterestAreas = new javax.swing.JLabel();
        scrollPanelInterestAreas = new javax.swing.JScrollPane();
        panelInterestAreas = new javax.swing.JPanel();
        labelDescription = new javax.swing.JLabel();
        scrollPanelDescription = new javax.swing.JScrollPane();
        textAreaDescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SubMeet_140x140.png"))); // NOI18N

        labelCMS.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelCMS.setForeground(new java.awt.Color(36, 105, 186));
        labelCMS.setText("CONFERENCE MANAGEMENT SYSTEM");

        panelBarra.setBackground(new java.awt.Color(204, 204, 204));
        panelBarra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBarra.setPreferredSize(new java.awt.Dimension(233, 23));

        homeButton.setBackground(new java.awt.Color(204, 204, 204));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-home-16.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.setPreferredSize(new java.awt.Dimension(20, 20));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(204, 204, 204));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-back-20.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        panelTitle.setBackground(new java.awt.Color(153, 153, 255));
        panelTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelTitle.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("INVIA PAPER");

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
                panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTitleLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        panelTitleLayout.setVerticalGroup(
                panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelTitle))
        );

        javax.swing.GroupLayout panelBarraLayout = new javax.swing.GroupLayout(panelBarra);
        panelBarra.setLayout(panelBarraLayout);
        panelBarraLayout.setHorizontalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBarraLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
        );
        panelBarraLayout.setVerticalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(backButton)
                                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        uploadPaperButton.setBackground(new java.awt.Color(153, 153, 255));
        uploadPaperButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        uploadPaperButton.setText("ALLEGA FILE");
        uploadPaperButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        uploadPaperButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadPaperButtonActionPerformed(evt);
            }
        });

        submitPaperButton.setBackground(new java.awt.Color(153, 153, 255));
        submitPaperButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitPaperButton.setText("INVIA");
        submitPaperButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        submitPaperButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitPaperButtonActionPerformed(evt);
            }
        });

        labelPaperTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPaperTitle.setText("Titolo Paper");

        fieldPaperTitle.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        fieldPaperTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldPaperTitleActionPerformed(evt);
            }
        });

        labelInterestAreas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInterestAreas.setText("Aree Di Interesse");

        javax.swing.GroupLayout panelInterestAreasLayout = new javax.swing.GroupLayout(panelInterestAreas);
        panelInterestAreas.setLayout(panelInterestAreasLayout);
        panelInterestAreasLayout.setHorizontalGroup(
                panelInterestAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 373, Short.MAX_VALUE)
        );
        panelInterestAreasLayout.setVerticalGroup(
                panelInterestAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
        );

        scrollPanelInterestAreas.setViewportView(panelInterestAreas);

        labelDescription.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelDescription.setText("Descrizione");

        textAreaDescription.setColumns(20);
        textAreaDescription.setRows(5);
        scrollPanelDescription.setViewportView(textAreaDescription);

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBarra, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(labelCMS))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(32, 32, 32)
                                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addComponent(labelPaperTitle)
                                                                .addComponent(fieldPaperTitle)
                                                                .addComponent(labelInterestAreas)
                                                                .addComponent(scrollPanelInterestAreas, javax.swing.GroupLayout.DEFAULT_SIZE, 385, Short.MAX_VALUE)
                                                                .addComponent(labelDescription)
                                                                .addComponent(scrollPanelDescription))
                                                        .addComponent(uploadPaperButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(155, 155, 155)
                                                .addComponent(submitPaperButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(53, Short.MAX_VALUE))
        );
        panelBackgroundLayout.setVerticalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(labelCMS)))
                                .addGap(18, 18, 18)
                                .addComponent(panelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelPaperTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldPaperTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addComponent(labelInterestAreas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPanelInterestAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelDescription)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPanelDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(uploadPaperButton)
                                .addGap(29, 29, 29)
                                .addComponent(submitPaperButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Navigate to home view
        homeControl.createHomeRouterView();
        this.dispose();
    }

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Navigate back to conference info view
        authorConferenceControl.showParticipationConferenceInfo(conference.getConferenceId());
        this.dispose();
    }

    private void submitPaperButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Get paper title and description
        String title = fieldPaperTitle.getText();
        String description = textAreaDescription.getText();

        // Validate input
        if (title == null || title.isBlank()) {
            new ErrorPopupView("Il titolo del paper non può essere vuoto.");
            return;
        }

        if (description == null || description.isBlank()) {
            new ErrorPopupView("La descrizione del paper non può essere vuota.");
            return;
        }

        if (selectedFile == null) {
            new ErrorPopupView("Devi allegare un file per il paper.");
            return;
        }

        // Get selected specializations
        StringBuilder specializationsBuilder = new StringBuilder();
        Component[] components = panelInterestAreas.getComponents();
        for (Component component : components) {
            if (component instanceof JCheckBox) {
                JCheckBox checkBox = (JCheckBox) component;
                if (checkBox.isSelected()) {
                    if (specializationsBuilder.length() > 0) {
                        specializationsBuilder.append(",");
                    }
                    specializationsBuilder.append(checkBox.getActionCommand()); // This contains the specializationId
                }
            }
        }
        String specializations = specializationsBuilder.toString();

        if (specializations.isEmpty()) {
            new ErrorPopupView("Devi selezionare almeno un'area di interesse.");
            return;
        }

        // Submit the paper
        if (authorConferenceControl.submitPaper(AppSession.getInstance().getUserId(), conference.getConferenceId(),
            title, description, specializations, selectedFile)) {
            this.dispose();
        }

    }

    private void fieldPaperTitleActionPerformed(java.awt.event.ActionEvent evt) {
        // No action needed
    }

    private void uploadPaperButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Create a file chooser
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleziona il file del paper");

        // Set file filter to only show PDF files
        fileChooser.setFileFilter(new javax.swing.filechooser.FileFilter() {
            @Override
            public boolean accept(File f) {
                return f.isDirectory() || f.getName().toLowerCase().endsWith(".pdf");
            }

            @Override
            public String getDescription() {
                return "PDF Files (*.pdf)";
            }
        });

        // Show the dialog and get the result
        int result = fileChooser.showOpenDialog(this);

        // If a file was selected, store it
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();
            uploadPaperButton.setText("FILE SELEZIONATO: " + selectedFile.getName());
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JButton backButton;
    private javax.swing.JTextField fieldPaperTitle;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel labelCMS;
    private javax.swing.JLabel labelDescription;
    private javax.swing.JLabel labelInterestAreas;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelPaperTitle;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelBarra;
    private javax.swing.JPanel panelInterestAreas;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JScrollPane scrollPanelDescription;
    private javax.swing.JScrollPane scrollPanelInterestAreas;
    private javax.swing.JButton submitPaperButton;
    private javax.swing.JTextArea textAreaDescription;
    private javax.swing.JButton uploadPaperButton;
    // End of variables declaration
}
