package com.submeet.client.notifiche.view;

import com.submeet.client.notifiche.controller.NotificationCenterControl;

import javax.swing.*;

public class FilterMenuView extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FilterMenuView.class.getName());
    private NotificationCenterControl control;
    private NotificationCenterView parent;


    /**
     * Creates new form FilterMenuView
     */
    public FilterMenuView(NotificationCenterControl control, NotificationCenterView parent) {
        super(parent, "Filtra notifiche", true);
        this.control = control;
        this.parent = parent;
        initComponents();

        this.setLocationRelativeTo(null);
        this.setVisible(true);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelCMS = new javax.swing.JLabel();
        panelBarra = new javax.swing.JPanel();
        labelText = new javax.swing.JLabel();
        scrollPanelMethod = new javax.swing.JScrollPane();
        listFilterParameters = new javax.swing.JList<>();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SubMeet_140x140.png"))); // NOI18N

        labelCMS.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelCMS.setForeground(new java.awt.Color(36, 105, 186));
        labelCMS.setText("CONFERENCE MANAGEMENT SYSTEM");

        panelBarra.setBackground(new java.awt.Color(204, 204, 204));
        panelBarra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBarra.setPreferredSize(new java.awt.Dimension(233, 23));

        javax.swing.GroupLayout panelBarraLayout = new javax.swing.GroupLayout(panelBarra);
        panelBarra.setLayout(panelBarraLayout);
        panelBarraLayout.setHorizontalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 482, Short.MAX_VALUE)
        );
        panelBarraLayout.setVerticalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 20, Short.MAX_VALUE)
        );

        labelText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelText.setText("SELEZIONA UN METODO DI FILTRAGGIO");

        scrollPanelMethod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scrollPanelMethod.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listFilterParameters.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Ripristina", "Visualizzata", "Non visualizzata", "Invito", "Invito PC", "Invito editore", "Invito sotto revisore" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });

        listFilterParameters.addListSelectionListener(e -> {
            if (!e.getValueIsAdjusting()) {
                String selectedValue = listFilterParameters.getSelectedValue();
                if (selectedValue != null) {
                    this.setFilter(selectedValue);
                }
            }
        });
        scrollPanelMethod.setViewportView(listFilterParameters);

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBarra, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(scrollPanelMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(63, 63, 63)
                                                .addComponent(labelText)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelCMS)
                                .addGap(0, 0, Short.MAX_VALUE))
        );
        panelBackgroundLayout.setVerticalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(labelCMS)))
                                .addGap(18, 18, 18)
                                .addComponent(panelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(labelText)
                                .addGap(18, 18, 18)
                                .addComponent(scrollPanelMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>

    private void setFilter(String selectedValue) {
        control.notificationFilter(selectedValue, parent);
        this.dispose();
    }

    // Variables declaration - do not modify
    private javax.swing.JLabel labelCMS;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelText;
    private javax.swing.JList<String> listFilterParameters;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelBarra;
    private javax.swing.JScrollPane scrollPanelMethod;
    // End of variables declaration
}
