/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.submeet.client.notifiche.view;

import com.submeet.client.account.controller.HomeControl;
import com.submeet.client.entity.EntityNotification;
import com.submeet.client.notifiche.controller.NotificationCenterControl;
import com.submeet.client.utility.AppSession;

import javax.swing.*;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.List;

/**
 *
 * @author aless
 */
public class NotificationCenterView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NotificationCenterView.class.getName());
    private NotificationCenterControl control;
    private List<EntityNotification> notifications;

    /**
     * Creates new form NotificationCenterView
     */
    public NotificationCenterView(List<EntityNotification> notifications, NotificationCenterControl control) {
        this.notifications = notifications;
        this.control = control;
        initComponents();
        setLocationRelativeTo(null);
        setSize(470, 530);
        setResizable(false);

        // layout verticale per “pile” di notifiche
        panelNotifiche.setLayout(
                new BoxLayout(panelNotifiche, BoxLayout.Y_AXIS)
        );
        panelNotifiche.setBorder(
                BorderFactory.createEmptyBorder(10,10,10,10)
        );

        displayNotifications(notifications);

        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        labelCMS = new javax.swing.JLabel();
        panelBarra = new javax.swing.JPanel();
        labelSchermata = new javax.swing.JLabel();
        homeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        panelNotifiche = new javax.swing.JPanel();
        filterButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBackground.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SubMeet_140x140.png"))); // NOI18N

        labelCMS.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelCMS.setForeground(new java.awt.Color(34, 94, 150));
        labelCMS.setText("CONFERENCE MANAGEMENT SYSTEM");

        panelBarra.setBackground(new java.awt.Color(204, 204, 204));

        labelSchermata.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        labelSchermata.setText("GESTIONE NOTIFICHE");

        homeButton.setBackground(new java.awt.Color(153, 153, 153));
        homeButton.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        homeButton.setText("HOME");
        homeButton.setMaximumSize(new java.awt.Dimension(75, 20));
        homeButton.setMinimumSize(new java.awt.Dimension(75, 20));
        homeButton.setPreferredSize(new java.awt.Dimension(75, 15));
        // Add action listener to home button
        homeButton.addActionListener(e -> {
            // Create HomeControl and show HomeRouterView
            HomeControl homeControl = new HomeControl();
            homeControl.createHomeRouterView();
            // Dispose this view
            this.dispose();
        });

        javax.swing.GroupLayout panelBarraLayout = new javax.swing.GroupLayout(panelBarra);
        panelBarra.setLayout(panelBarraLayout);
        panelBarraLayout.setHorizontalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBarraLayout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(labelSchermata, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
        );
        panelBarraLayout.setVerticalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelSchermata)
                                        .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        panelNotifiche.setBackground(new java.awt.Color(153, 153, 255));

        javax.swing.GroupLayout panelNotificheLayout = new javax.swing.GroupLayout(panelNotifiche);
        panelNotifiche.setLayout(panelNotificheLayout);
        panelNotificheLayout.setHorizontalGroup(
                panelNotificheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 366, Short.MAX_VALUE)
        );
        panelNotificheLayout.setVerticalGroup(
                panelNotificheLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 371, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panelNotifiche);

        filterButton.setBackground(new java.awt.Color(34, 94, 150));
        filterButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        filterButton.setText("FILTRA");
        filterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                                .addComponent(labelCMS)
                                .addGap(52, 52, 52))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(filterButton)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(13, 13, 13)
                                                .addComponent(labelCMS)))
                                .addGap(18, 18, 18)
                                .addComponent(panelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(filterButton)))
                                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelBackgroundLayout.setVerticalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>


    public void displayNotifications(List<EntityNotification> notificheDalDB) {
        panelNotifiche.removeAll();

        for (EntityNotification ntf : notificheDalDB) {
            String testo = ntf.getText();
            String preview = testo.length() > 100
                    ? testo.substring(0, 100) + "…"
                    : testo;

            String dataStr = ntf.getDate() != null
                    ? new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm").format(ntf.getDate())
                    : "Data non disponibile";

            // pannello singola notifica
            JPanel item = new JPanel(new BorderLayout(8, 4));
            item.setBorder(BorderFactory.createLineBorder(Color.LIGHT_GRAY));
            item.setMaximumSize(new Dimension(300, 60));
            item.setPreferredSize(new Dimension(300, 60));
            item.setBackground(ntf.isVisualized() ? new Color(210, 210, 210) : Color.WHITE); // Grigio se già letta

            // contenitore verticale per testo + data
            JPanel textPanel = new JPanel();
            textPanel.setLayout(new BoxLayout(textPanel, BoxLayout.Y_AXIS));
            textPanel.setOpaque(false);

            JLabel lblPreview = new JLabel("<html><b>" + preview + "</b></html>");
            lblPreview.setAlignmentX(LEFT_ALIGNMENT);

            JLabel lblDate = new JLabel(dataStr);
            lblDate.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 10));
            lblDate.setForeground(Color.DARK_GRAY);
            lblDate.setAlignmentX(LEFT_ALIGNMENT);

            textPanel.add(lblPreview);
            textPanel.add(lblDate);

            item.add(textPanel, BorderLayout.CENTER);

            // Add click listener to show full notification
            final int notifId = ntf.getNotificId();
            item.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
            item.addMouseListener(new MouseAdapter() {
                @Override
                public void mouseClicked(MouseEvent e) {
                    showFullNotification(notifId);
                }
            });

            // spazio e aggiunta
            panelNotifiche.add(Box.createRigidArea(new Dimension(0, 5)));
            panelNotifiche.add(item);
        }

        panelNotifiche.revalidate();
        panelNotifiche.repaint();
    }

    public void showFullNotification(int notifId) {
        // Create NotificationCenterControl and show full notification
        NotificationCenterControl control = new NotificationCenterControl(AppSession.getInstance().getUserId());
        control.viewNotification(notifId);
        // Close this view
        this.dispose();
    }

    public void filterButtonActionPerformed(java.awt.event.ActionEvent evt) {
        control.createFilterMenu(this);
    }

    // Variables declaration - do not modify
    private javax.swing.JButton homeButton;
    private javax.swing.JButton filterButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelCMS;
    private javax.swing.JLabel labelSchermata;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelBarra;
    private javax.swing.JPanel panelNotifiche;
    // End of variables declaration
}
