package com.submeet.client.revisore.view;

import com.submeet.client.common.ErrorPopupView;
import com.submeet.client.entity.EntityReview;
import com.submeet.client.revisore.controller.ReviewerConferenceControl;

public class CompletedReviewView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CompletedReviewView.class.getName());
    private ReviewerConferenceControl reviewerConferenceControl;
    private EntityReview review;
    private boolean isSubReview = false;

    /**
     * Creates new form CompletedReviewView
     */
    public CompletedReviewView(ReviewerConferenceControl reviewerConferenceControl, EntityReview review, boolean isSubReview) {
        this.reviewerConferenceControl = reviewerConferenceControl;
        this.review = review;
        this.isSubReview = isSubReview;
        initComponents();
        setResizable(false);

        // Populate fields with data from the review
        populateFields();

        setLocationRelativeTo(null);
        setVisible(true);
    }

    /**
     * Populates the UI components with data from the review
     */
    private void populateFields() {
        if (review != null) {
            // Set paper title
            fieldPaperTitle.setText(review.getTitle());
            fieldPaperTitle.setDisabledTextColor(new java.awt.Color(0, 0, 0));

            // Set review text
            textAreaReview.setText(review.getReviewComment());

            // Set private comment
            textAreaPrivateComment.setText(review.getPrivateComment());

            // Set rating stars
            int rating = review.getRating();

            // Disable all toggle buttons
            toggleButtonStar1.setEnabled(false);
            toggleButtonStar2.setEnabled(false);
            toggleButtonStar3.setEnabled(false);
            toggleButtonStar4.setEnabled(false);
            toggleButtonStar5.setEnabled(false);

            // Set selected state based on rating
            toggleButtonStar1.setSelected(rating >= 1);
            toggleButtonStar2.setSelected(rating >= 2);
            toggleButtonStar3.setSelected(rating >= 3);
            toggleButtonStar4.setSelected(rating >= 4);
            toggleButtonStar5.setSelected(rating >= 5);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelCMS = new javax.swing.JLabel();
        panelBarra = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        labelPaperTitle = new javax.swing.JLabel();
        fieldPaperTitle = new javax.swing.JTextField();
        labelRating = new javax.swing.JLabel();
        scrollPanelReview = new javax.swing.JScrollPane();
        textAreaReview = new javax.swing.JTextArea();
        labelReview = new javax.swing.JLabel();
        labelPrivateComment = new javax.swing.JLabel();
        scrollPanelPrivateComment = new javax.swing.JScrollPane();
        textAreaPrivateComment = new javax.swing.JTextArea();
        othersReviewButton = new javax.swing.JButton();
        downloadPaperButton = new javax.swing.JButton();
        toggleButtonStar1 = new javax.swing.JToggleButton();
        toggleButtonStar2 = new javax.swing.JToggleButton();
        toggleButtonStar3 = new javax.swing.JToggleButton();
        toggleButtonStar4 = new javax.swing.JToggleButton();
        toggleButtonStar5 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SubMeet_140x140.png"))); // NOI18N

        labelCMS.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelCMS.setForeground(new java.awt.Color(36, 105, 186));
        labelCMS.setText("CONFERENCE MANAGEMENT SYSTEM");

        panelBarra.setBackground(new java.awt.Color(204, 204, 204));
        panelBarra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBarra.setPreferredSize(new java.awt.Dimension(233, 23));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-home-16.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setPreferredSize(new java.awt.Dimension(20, 20));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-back-20.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel7.setBackground(new java.awt.Color(153, 153, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("REVISIONE COMPLETATA");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
                jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel10))
        );

        javax.swing.GroupLayout panelBarraLayout = new javax.swing.GroupLayout(panelBarra);
        panelBarra.setLayout(panelBarraLayout);
        panelBarraLayout.setHorizontalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBarraLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
        );
        panelBarraLayout.setVerticalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButton2)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        labelPaperTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPaperTitle.setText("Titolo paper");

        fieldPaperTitle.setEditable(false);
        fieldPaperTitle.setMaximumSize(new java.awt.Dimension(360, 22));

        labelRating.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelRating.setText("Valutazione:");

        textAreaReview.setColumns(20);
        textAreaReview.setLineWrap(true);
        textAreaReview.setRows(5);
        textAreaReview.setEditable(false);
        scrollPanelReview.setViewportView(textAreaReview);

        labelReview.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelReview.setText("Revisione");

        labelPrivateComment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPrivateComment.setText("Commento privato");

        textAreaPrivateComment.setColumns(20);
        textAreaPrivateComment.setLineWrap(true);
        textAreaPrivateComment.setRows(5);
        textAreaPrivateComment.setEditable(false);
        scrollPanelPrivateComment.setViewportView(textAreaPrivateComment);

        othersReviewButton.setBackground(new java.awt.Color(153, 153, 255));
        othersReviewButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        othersReviewButton.setText("<html><center>VISUALIZZA REVISIONI<br>ALTRUI</center></html>");
        othersReviewButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        othersReviewButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        othersReviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                othersReviewButtonActionPerformed(evt);
            }
        });

        downloadPaperButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-download-16.png"))); // NOI18N
        downloadPaperButton.setBorderPainted(false);
        downloadPaperButton.setContentAreaFilled(false);
        downloadPaperButton.setMaximumSize(new java.awt.Dimension(16, 16));
        downloadPaperButton.setMinimumSize(new java.awt.Dimension(16, 16));
        downloadPaperButton.setPreferredSize(new java.awt.Dimension(16, 16));
        downloadPaperButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downloadPaperButtonActionPerformed(evt);
            }
        });

        toggleButtonStar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-star-24.png"))); // NOI18N
        toggleButtonStar1.setBorder(null);
        toggleButtonStar1.setBorderPainted(false);
        toggleButtonStar1.setContentAreaFilled(false);
        toggleButtonStar1.setFocusPainted(false);
        toggleButtonStar1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-christmas-star-24.png"))); // NOI18N

        toggleButtonStar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-star-24.png"))); // NOI18N
        toggleButtonStar2.setBorder(null);
        toggleButtonStar2.setBorderPainted(false);
        toggleButtonStar2.setContentAreaFilled(false);
        toggleButtonStar2.setFocusPainted(false);
        toggleButtonStar2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-christmas-star-24.png"))); // NOI18N

        toggleButtonStar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-star-24.png"))); // NOI18N
        toggleButtonStar3.setBorder(null);
        toggleButtonStar3.setBorderPainted(false);
        toggleButtonStar3.setContentAreaFilled(false);
        toggleButtonStar3.setFocusPainted(false);
        toggleButtonStar3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-christmas-star-24.png"))); // NOI18N

        toggleButtonStar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-star-24.png"))); // NOI18N
        toggleButtonStar4.setBorder(null);
        toggleButtonStar4.setBorderPainted(false);
        toggleButtonStar4.setContentAreaFilled(false);
        toggleButtonStar4.setFocusPainted(false);
        toggleButtonStar4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-christmas-star-24.png"))); // NOI18N

        toggleButtonStar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-star-24.png"))); // NOI18N
        toggleButtonStar5.setBorder(null);
        toggleButtonStar5.setBorderPainted(false);
        toggleButtonStar5.setContentAreaFilled(false);
        toggleButtonStar5.setFocusPainted(false);
        toggleButtonStar5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-christmas-star-24.png"))); // NOI18N

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBarra, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(labelCMS))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(labelPaperTitle)
                                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                                .addComponent(fieldPaperTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(downloadPaperButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                                .addComponent(labelRating)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(toggleButtonStar1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(toggleButtonStar2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(toggleButtonStar3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(toggleButtonStar4)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(toggleButtonStar5))
                                                        .addComponent(labelReview)
                                                        .addComponent(labelPrivateComment)
                                                        .addComponent(othersReviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(scrollPanelPrivateComment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                                                .addComponent(scrollPanelReview, javax.swing.GroupLayout.Alignment.LEADING)))))
                                .addContainerGap(49, Short.MAX_VALUE))
        );
        panelBackgroundLayout.setVerticalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addComponent(labelCMS)))
                                .addGap(18, 18, 18)
                                .addComponent(panelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelPaperTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(fieldPaperTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(downloadPaperButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(labelReview)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPanelReview, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(labelRating)
                                        .addComponent(toggleButtonStar1)
                                        .addComponent(toggleButtonStar2)
                                        .addComponent(toggleButtonStar3)
                                        .addComponent(toggleButtonStar4)
                                        .addComponent(toggleButtonStar5))
                                .addGap(31, 31, 31)
                                .addComponent(labelPrivateComment)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPanelPrivateComment, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(othersReviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        // Return to home screen using the ReviewerConferenceControl
        if (reviewerConferenceControl != null) {
            // Close this view
            this.dispose();
            // Return to home
            reviewerConferenceControl.returnToHome();
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        // Go back to the previous screen
        if (reviewerConferenceControl != null) {
            // Close this view
            this.dispose();
            // Show the reviewer dashboard view
            if(!isSubReview)
                reviewerConferenceControl.showReviewerDashboardView();
            else
                reviewerConferenceControl.returnToReviewerView();
        }
    }

    private void othersReviewButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Show other reviews for this paper
        if (reviewerConferenceControl != null && review != null) {
            // Show the other reviews view
            if(!isSubReview) {
                this.dispose();
                reviewerConferenceControl.showOtherReviewView(review.getPaperId(), review.getTitle());
            }
            else
                new ErrorPopupView("Non puoi vedere revisioni altrui se sei un sotto revisore");
        }
    }

    private void downloadPaperButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Download the paper using the ReviewerConferenceControl
        if (reviewerConferenceControl != null && review != null) {
            boolean success = reviewerConferenceControl.downloadPaper(review.getPaperId(), review.getTitle());
            if (!success) {
                new ErrorPopupView("Download del file fallito");
            }
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JButton downloadPaperButton;
    private javax.swing.JTextField fieldPaperTitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JLabel labelCMS;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelPaperTitle;
    private javax.swing.JLabel labelPrivateComment;
    private javax.swing.JLabel labelRating;
    private javax.swing.JLabel labelReview;
    private javax.swing.JButton othersReviewButton;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelBarra;
    private javax.swing.JScrollPane scrollPanelPrivateComment;
    private javax.swing.JScrollPane scrollPanelReview;
    private javax.swing.JTextArea textAreaPrivateComment;
    private javax.swing.JTextArea textAreaReview;
    private javax.swing.JToggleButton toggleButtonStar1;
    private javax.swing.JToggleButton toggleButtonStar2;
    private javax.swing.JToggleButton toggleButtonStar3;
    private javax.swing.JToggleButton toggleButtonStar4;
    private javax.swing.JToggleButton toggleButtonStar5;
    // End of variables declaration
}
