package com.submeet.client.revisore.view;

import java.awt.event.ActionListener;

public class ConferenceView extends javax.swing.JFrame {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConferenceView.class.getName());

    public ConferenceView() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * Sets the conference name in the view
     * @param name The name of the conference
     */
    public void setConferenceName(String name) {
        labelSetConferenceName.setText(name);
    }

    /**
     * Sets the interest areas in the view
     * @param areas The interest areas of the conference
     */
    public void setInterestAreas(String areas) {
        labelSetInterestAreas.setText(areas);
    }

    /**
     * Sets the conference date in the view
     * @param date The date of the conference
     */
    public void setConferenceDate(String date) {
        labelSetConferenceDate.setText(date);
    }

    /**
     * Sets the submission expiration date in the view
     * @param date The submission expiration date
     */
    public void setSubmissionExpirationDate(String date) {
        labelSetSubmissionExpirationDate.setText(date);
    }

    /**
     * Sets the review expiration date in the view
     * @param date The review expiration date
     */
    public void setReviewExpirationDate(String date) {
        labelSetReviewExpirationDate.setText(date);
    }

    /**
     * Sets the final version expiration date in the view
     * @param date The final version expiration date
     */
    public void setFinalVersionExpirationDate(String date) {
        labelSetFinalVersionExpirationDate.setText(date);
    }

    /**
     * Sets the languages in the view
     * @param languages The languages of the conference
     */
    public void setLanguages(String languages) {
        labelSetLanguages.setText(languages);
    }

    /**
     * Sets the maximum number of reviewers in the view
     * @param maxReviewer The maximum number of reviewers
     */
    public void setMaxReviewer(String maxReviewer) {
        labelSetMaxReviewer.setText(maxReviewer);
    }

    /**
     * Sets the action for the home button
     * @param listener The action listener for the home button
     */
    public void setHomeButtonAction(ActionListener listener) {
        homeButton.addActionListener(listener);
    }

    /**
     * Sets the action for the back button
     * @param listener The action listener for the back button
     */
    public void setBackButtonAction(ActionListener listener) {
        backButton.addActionListener(listener);
    }

    public void setDashboardReviewButtonAction(ActionListener listener) {
        dashboardReviewButton.addActionListener(listener);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelCMS = new javax.swing.JLabel();
        panelBarra = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        panelTitle = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        panelFields = new javax.swing.JPanel();
        labelConferenceName = new javax.swing.JLabel();
        labelSetConferenceName = new javax.swing.JLabel();
        labelInterestAreas = new javax.swing.JLabel();
        labelSetInterestAreas = new javax.swing.JLabel();
        labelSubmissionExpirationDate = new javax.swing.JLabel();
        labelReviewExpirationDate = new javax.swing.JLabel();
        labelFialVersionExpirationDate = new javax.swing.JLabel();
        labelLanguages = new javax.swing.JLabel();
        labelMaxReviewer = new javax.swing.JLabel();
        labelSetSubmissionExpirationDate = new javax.swing.JLabel();
        labelSetReviewExpirationDate = new javax.swing.JLabel();
        labelSetFinalVersionExpirationDate = new javax.swing.JLabel();
        labelSetLanguages = new javax.swing.JLabel();
        labelSetMaxReviewer = new javax.swing.JLabel();
        labelConferenceDate = new javax.swing.JLabel();
        labelSetConferenceDate = new javax.swing.JLabel();
        dashboardReviewButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SubMeet_140x140.png"))); // NOI18N

        labelCMS.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelCMS.setForeground(new java.awt.Color(36, 105, 186));
        labelCMS.setText("CONFERENCE MANAGEMENT SYSTEM");

        panelBarra.setBackground(new java.awt.Color(204, 204, 204));
        panelBarra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBarra.setPreferredSize(new java.awt.Dimension(233, 23));

        homeButton.setBackground(new java.awt.Color(204, 204, 204));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-home-16.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.setPreferredSize(new java.awt.Dimension(20, 20));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(204, 204, 204));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-back-20.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        panelTitle.setBackground(new java.awt.Color(153, 153, 255));
        panelTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelTitle.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("INFORMAZIONI");

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
                panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTitleLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
        );
        panelTitleLayout.setVerticalGroup(
                panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelTitle))
        );

        javax.swing.GroupLayout panelBarraLayout = new javax.swing.GroupLayout(panelBarra);
        panelBarra.setLayout(panelBarraLayout);
        panelBarraLayout.setHorizontalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBarraLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
        );
        panelBarraLayout.setVerticalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(backButton)
                                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        panelFields.setBackground(new java.awt.Color(153, 153, 255));

        labelConferenceName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelConferenceName.setText("Nome Conferenza:");

        labelSetConferenceName.setMaximumSize(new java.awt.Dimension(380, 16));

        labelInterestAreas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInterestAreas.setText("Aree Specialistiche");

        labelSetInterestAreas.setMaximumSize(new java.awt.Dimension(380, 16));

        labelSubmissionExpirationDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelSubmissionExpirationDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubmissionExpirationDate.setText("Data Scadenza Sottomissioni:");

        labelReviewExpirationDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelReviewExpirationDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelReviewExpirationDate.setText("Data Scadenza Revisioni:");

        labelFialVersionExpirationDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelFialVersionExpirationDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFialVersionExpirationDate.setText("Data Scadenza Sottomissioni Versioni Finali:");

        labelLanguages.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelLanguages.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLanguages.setText("Lingue:");

        labelMaxReviewer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelMaxReviewer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMaxReviewer.setText("N° Revisori Per Articolo (MAX):");

        labelSetSubmissionExpirationDate.setMaximumSize(new java.awt.Dimension(145, 16));

        labelSetReviewExpirationDate.setMaximumSize(new java.awt.Dimension(145, 16));

        labelSetFinalVersionExpirationDate.setMaximumSize(new java.awt.Dimension(145, 16));

        labelSetLanguages.setMaximumSize(new java.awt.Dimension(145, 16));

        labelConferenceDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelConferenceDate.setText("Data Conferenza:");

        javax.swing.GroupLayout panelFieldsLayout = new javax.swing.GroupLayout(panelFields);
        panelFields.setLayout(panelFieldsLayout);
        panelFieldsLayout.setHorizontalGroup(
                panelFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFieldsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelConferenceName)
                                        .addComponent(labelSetConferenceName, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(labelInterestAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelFieldsLayout.createSequentialGroup()
                                                .addComponent(labelMaxReviewer)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelSetMaxReviewer, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelFieldsLayout.createSequentialGroup()
                                                .addComponent(labelLanguages)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelSetLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelFieldsLayout.createSequentialGroup()
                                                .addComponent(labelFialVersionExpirationDate)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelSetFinalVersionExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelFieldsLayout.createSequentialGroup()
                                                .addComponent(labelReviewExpirationDate)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelSetReviewExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelFieldsLayout.createSequentialGroup()
                                                .addComponent(labelSubmissionExpirationDate)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelSetSubmissionExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelFieldsLayout.createSequentialGroup()
                                                .addComponent(labelConferenceDate)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(labelSetConferenceDate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(labelSetInterestAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelFieldsLayout.setVerticalGroup(
                panelFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelFieldsLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelConferenceName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSetConferenceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelInterestAreas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSetInterestAreas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelConferenceDate)
                                        .addComponent(labelSetConferenceDate))
                                .addGap(18, 18, 18)
                                .addGroup(panelFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelSubmissionExpirationDate)
                                        .addComponent(labelSetSubmissionExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelReviewExpirationDate)
                                        .addComponent(labelSetReviewExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelFialVersionExpirationDate)
                                        .addComponent(labelSetFinalVersionExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(panelFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelLanguages)
                                        .addComponent(labelSetLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(26, 26, 26)
                                .addGroup(panelFieldsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(labelMaxReviewer)
                                        .addComponent(labelSetMaxReviewer))
                                .addContainerGap(20, Short.MAX_VALUE))
        );

        dashboardReviewButton.setBackground(new java.awt.Color(153, 153, 255));
        dashboardReviewButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        dashboardReviewButton.setText("REVISIONI");
        dashboardReviewButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dashboardReviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardReviewButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBarra, javax.swing.GroupLayout.DEFAULT_SIZE, 480, Short.MAX_VALUE)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(12, 12, 12)
                                                .addComponent(labelCMS))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(panelFields, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(174, 174, 174)
                                                .addComponent(dashboardReviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(69, Short.MAX_VALUE))
        );
        panelBackgroundLayout.setVerticalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(labelCMS)))
                                .addGap(18, 18, 18)
                                .addComponent(panelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(panelFields, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addComponent(dashboardReviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // This will be handled by the setHomeButtonAction method
        this.dispose();
    }

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // This will be handled by the setBackButtonAction method
        this.dispose();
    }

    private void dashboardReviewButtonActionPerformed(java.awt.event.ActionEvent evt) {
        this.dispose();
    }

    // Variables declaration - do not modify
    private javax.swing.JButton backButton;
    private javax.swing.JButton dashboardReviewButton;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel labelCMS;
    private javax.swing.JLabel labelConferenceDate;
    private javax.swing.JLabel labelConferenceName;
    private javax.swing.JLabel labelFialVersionExpirationDate;
    private javax.swing.JLabel labelInterestAreas;
    private javax.swing.JLabel labelLanguages;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelMaxReviewer;
    private javax.swing.JLabel labelReviewExpirationDate;
    private javax.swing.JLabel labelSetConferenceDate;
    private javax.swing.JLabel labelSetConferenceName;
    private javax.swing.JLabel labelSetFinalVersionExpirationDate;
    private javax.swing.JLabel labelSetInterestAreas;
    private javax.swing.JLabel labelSetLanguages;
    private javax.swing.JLabel labelSetMaxReviewer;
    private javax.swing.JLabel labelSetReviewExpirationDate;
    private javax.swing.JLabel labelSetSubmissionExpirationDate;
    private javax.swing.JLabel labelSubmissionExpirationDate;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelBarra;
    private javax.swing.JPanel panelFields;
    private javax.swing.JPanel panelTitle;
    // End of variables declaration
}
