package com.submeet.client.revisore.view;

import com.submeet.client.entity.EntityPaper;
import com.submeet.client.revisore.controller.ReviewerConferenceControl;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class OfferAssignView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OfferAssignView.class.getName());
    private ReviewerConferenceControl reviewerConferenceControl;
    private String conferenceTitle;
    private ArrayList<EntityPaper> unassignedPapers;

    /**
     * Creates new form OfferAssignView
     */
    public OfferAssignView(ReviewerConferenceControl reviewerConferenceControl, ArrayList<EntityPaper> unassignedPapers, String conferenceTitle) {
        this.reviewerConferenceControl = reviewerConferenceControl;
        this.unassignedPapers = unassignedPapers;
        this.conferenceTitle = conferenceTitle;
        initComponents();
        setResizable(false);

        this.dipsplayPapers();

        this.setLocationRelativeTo(null);
        this.setVisible(true);
    }

    public void dipsplayPapers() {
        this.fieldConference.setText(conferenceTitle);
        this.fieldConference.setEditable(false);
        this.fieldConference.setDisabledTextColor(new java.awt.Color(0, 0, 0));

        DefaultTableModel model = new DefaultTableModel(new Object[]{"Autore", "Titolo", "Preferenza", "Conflitto"}, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return column == 2 || column == 3; // Solo Preference e Conflict editabili
            }

            @Override
            public Class<?> getColumnClass(int columnIndex) {
                return switch (columnIndex) {
                    case 3 -> Boolean.class; // JCheckBox
                    default -> String.class;
                };
            }
        };
        model.setRowCount(0); // Clear the table

        model.addTableModelListener(e -> {
            int row = e.getFirstRow();
            int column = e.getColumn();

            // Solo se è la colonna di preferenza o conflitto
            if (column == 2 || column == 3) {
                String prefValue = (String) model.getValueAt(row, 2);
                Boolean conflict = (Boolean) model.getValueAt(row, 3);

                // Se conflitto è true, forza preferenza a "0"
                if (column == 3 && conflict != null && conflict) {
                    if (!"0".equals(prefValue)) {
                        model.setValueAt("0", row, 2);
                    }
                }

                // Se preferenza > 0, forza conflitto a false
                if (column == 2 && prefValue != null && !"0".equals(prefValue)) {
                    if (conflict != null && conflict) {
                        model.setValueAt(false, row, 3);
                    }
                }
            }
        });

        tablePapers.setModel(model);

        // Preference column (index 2): ComboBox
        JComboBox<String> preferenceBox = new JComboBox<>(new String[]{"0", "1", "2", "3", "4", "5"});
        tablePapers.getColumnModel().getColumn(2).setCellEditor(new DefaultCellEditor(preferenceBox));

        // Conflict column (index 3): CheckBox
        tablePapers.getColumnModel().getColumn(3).setCellEditor(new DefaultCellEditor(new JCheckBox()));

        if (unassignedPapers != null && !unassignedPapers.isEmpty()) {
            for (EntityPaper paper : unassignedPapers) {

                model.addRow(new Object[]{
                        paper.getAuthorName() + " " + paper.getAuthorSurname(),
                        paper.getTitle(),
                        "0",
                        false
                });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelCMS = new javax.swing.JLabel();
        panelBarra = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        panelTitle = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelConference = new javax.swing.JLabel();
        fieldConference = new javax.swing.JTextField();
        scrollPanelPaper = new javax.swing.JScrollPane();
        tablePapers = new javax.swing.JTable();
        labelPapers = new javax.swing.JLabel();
        preferencesButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SubMeet_140x140.png"))); // NOI18N

        labelCMS.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelCMS.setForeground(new java.awt.Color(36, 105, 186));
        labelCMS.setText("CONFERENCE MANAGEMENT SYSTEM");

        panelBarra.setBackground(new java.awt.Color(204, 204, 204));
        panelBarra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBarra.setPreferredSize(new java.awt.Dimension(233, 23));

        homeButton.setBackground(new java.awt.Color(204, 204, 204));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-home-16.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.setPreferredSize(new java.awt.Dimension(20, 20));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(204, 204, 204));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-back-20.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        panelTitle.setBackground(new java.awt.Color(153, 153, 255));
        panelTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelTitle.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("OFFERTA");

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
                panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
        );
        panelTitleLayout.setVerticalGroup(
                panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelTitle))
        );

        javax.swing.GroupLayout panelBarraLayout = new javax.swing.GroupLayout(panelBarra);
        panelBarra.setLayout(panelBarraLayout);
        panelBarraLayout.setHorizontalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBarraLayout.createSequentialGroup()
                                .addGap(34, 34, 34)
                                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
        );
        panelBarraLayout.setVerticalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(backButton)
                                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        labelConference.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelConference.setText("Conferenza");

        fieldConference.setMaximumSize(new java.awt.Dimension(360, 22));

        scrollPanelPaper.setBackground(new java.awt.Color(255, 255, 255));

        tablePapers.setModel(new javax.swing.table.DefaultTableModel(
                new Object [][] {
                        {null, null, null, null}
                },
                new String [] {
                        "AUTORE", "TITOLO PAPER", "LIVELLO INTERESSE", "CONFLITTO INTERESSE"
                }
        ) {
            boolean[] canEdit = new boolean [] {
                    false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrollPanelPaper.setViewportView(tablePapers);

        labelPapers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPapers.setText("Paper");

        preferencesButton.setBackground(new java.awt.Color(153, 153, 255));
        preferencesButton.setText("ESPRIMI PREFERENZE");
        preferencesButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        preferencesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preferencesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBarra, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelCMS)
                                .addGap(168, 168, 168))
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(38, 38, 38)
                                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(labelConference)
                                                        .addComponent(labelPapers)
                                                        .addComponent(scrollPanelPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 633, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(fieldConference, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(283, 283, 283)
                                                .addComponent(preferencesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(38, Short.MAX_VALUE))
        );
        panelBackgroundLayout.setVerticalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(26, 26, 26)
                                                .addComponent(labelCMS)))
                                .addGap(18, 18, 18)
                                .addComponent(panelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelConference)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldConference, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelPapers)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPanelPaper, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(preferencesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        reviewerConferenceControl.returnToHome();
        this.dispose();
    }

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {
        reviewerConferenceControl.showReviewerDashboardView();
        this.dispose();
    }

    private void preferencesButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Extract papers with preference and/or conflict
        List<Integer> paperIds = new ArrayList<>();
        List<Integer> preferences = new ArrayList<>();
        List<Boolean> conflicts = new ArrayList<>();

        DefaultTableModel model = (DefaultTableModel) tablePapers.getModel();

        for (int i = 0; i < model.getRowCount(); i++) {
            // Get paper ID from unassignedPapers (assumed same order as table rows)
            int paperId = unassignedPapers.get(i).getPaperId();

            // Get preference from JComboBox
            String preferenceStr = (String) model.getValueAt(i, 2);
            int preference = Integer.parseInt(preferenceStr);

            // Get conflict from JCheckBox
            Boolean conflict = (Boolean) tablePapers.getValueAt(i, 3);

            // Skip if preference is 0 and no conflict
            if (preference == 0 && !conflict) {
                continue;
            }

            paperIds.add(paperId);
            preferences.add(preference);
            conflicts.add(conflict);
        }

        reviewerConferenceControl.confirmInterest(paperIds, preferences, conflicts);
        this.dispose();
    }

    // Variables declaration - do not modify
    private javax.swing.JButton backButton;
    private javax.swing.JTextField fieldConference;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel labelCMS;
    private javax.swing.JLabel labelConference;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelPapers;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelBarra;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JButton preferencesButton;
    private javax.swing.JScrollPane scrollPanelPaper;
    private javax.swing.JTable tablePapers;
    // End of variables declaration
}

