package com.submeet.client.revisore.view;

import com.submeet.client.common.ErrorPopupView;
import com.submeet.client.revisore.controller.ReviewerConferenceControl;
import com.submeet.client.utility.AppSession;
import com.submeet.client.utility.SystemNotification;

import javax.swing.*;

public class OnGoingReviewView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(OnGoingReviewView.class.getName());
    private ReviewerConferenceControl reviewerConferenceControl;
    private String paperTitle;
    private int paperId;
    private int reviewId;
    private int currentRating = 0;
    private boolean isSubReview = false;

    /**
     * Creates new form OnGoingReviewView
     */
    public OnGoingReviewView(ReviewerConferenceControl reviewerConferenceControl, int paperId, String paperTitle, int reviewId, boolean isSubReview) {
        this.reviewId = reviewId;
        this.reviewerConferenceControl = reviewerConferenceControl;
        this.paperTitle = paperTitle;
        this.paperId = paperId;
        this.isSubReview = isSubReview;

        initComponents();
        setResizable(false);

        // Populate fields with data
        populateFields();

        setLocationRelativeTo(null);

        setVisible(true);
    }

    /**
     * Populates the UI components with data
     */
    private void populateFields() {
        // Set paper title
        fieldPaperTitle.setText(paperTitle);
        fieldPaperTitle.setDisabledTextColor(new java.awt.Color(0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelCMS = new javax.swing.JLabel();
        panelBarra = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        panelTitle = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelPaperTitle = new javax.swing.JLabel();
        fieldPaperTitle = new javax.swing.JTextField();
        labelRating = new javax.swing.JLabel();
        scrollPanelReview = new javax.swing.JScrollPane();
        textAreaReview = new javax.swing.JTextArea();
        labelReview = new javax.swing.JLabel();
        labelPrivateComment = new javax.swing.JLabel();
        scrollPanelPrivateComment = new javax.swing.JScrollPane();
        textAreaPrivateComment = new javax.swing.JTextArea();
        submitReviewButton = new javax.swing.JButton();
        paperDownloadButton = new javax.swing.JButton();
        toggleButtonStar1 = new javax.swing.JToggleButton();
        toggleButtonStar2 = new javax.swing.JToggleButton();
        toggleButtonStar3 = new javax.swing.JToggleButton();
        toggleButtonStar4 = new javax.swing.JToggleButton();
        toggleButtonStar5 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SubMeet_140x140.png"))); // NOI18N

        labelCMS.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelCMS.setForeground(new java.awt.Color(36, 105, 186));
        labelCMS.setText("CONFERENCE MANAGEMENT SYSTEM");

        panelBarra.setBackground(new java.awt.Color(204, 204, 204));
        panelBarra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBarra.setPreferredSize(new java.awt.Dimension(233, 23));

        homeButton.setBackground(new java.awt.Color(204, 204, 204));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-home-16.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.setPreferredSize(new java.awt.Dimension(20, 20));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(204, 204, 204));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-back-20.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        panelTitle.setBackground(new java.awt.Color(153, 153, 255));
        panelTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelTitle.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("REVISIONE IN CORSO");

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
                panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTitleLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                .addContainerGap())
        );
        panelTitleLayout.setVerticalGroup(
                panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelTitle))
        );

        javax.swing.GroupLayout panelBarraLayout = new javax.swing.GroupLayout(panelBarra);
        panelBarra.setLayout(panelBarraLayout);
        panelBarraLayout.setHorizontalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBarraLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
        );
        panelBarraLayout.setVerticalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelTitle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(backButton)
                                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        labelPaperTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPaperTitle.setText("Titolo paper");

        fieldPaperTitle.setEditable(false);
        fieldPaperTitle.setMaximumSize(new java.awt.Dimension(360, 22));

        labelRating.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelRating.setText("Valutazione:");

        textAreaReview.setColumns(20);
        textAreaReview.setLineWrap(true);
        textAreaReview.setRows(5);
        scrollPanelReview.setViewportView(textAreaReview);

        labelReview.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelReview.setText("Revisione");

        labelPrivateComment.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPrivateComment.setText("Commento privato");

        textAreaPrivateComment.setColumns(20);
        textAreaPrivateComment.setRows(5);
        scrollPanelPrivateComment.setViewportView(textAreaPrivateComment);

        submitReviewButton.setBackground(new java.awt.Color(153, 153, 255));
        submitReviewButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        submitReviewButton.setText("INOLTRA REVISIONE");
        submitReviewButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        submitReviewButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        submitReviewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitReviewButtonActionPerformed(evt);
            }
        });

        paperDownloadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-download-16.png"))); // NOI18N
        paperDownloadButton.setBorderPainted(false);
        paperDownloadButton.setContentAreaFilled(false);
        paperDownloadButton.setMaximumSize(new java.awt.Dimension(16, 16));
        paperDownloadButton.setMinimumSize(new java.awt.Dimension(16, 16));
        paperDownloadButton.setPreferredSize(new java.awt.Dimension(16, 16));
        paperDownloadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paperDownloadButtonActionPerformed(evt);
            }
        });

        toggleButtonStar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-star-24.png"))); // NOI18N
        toggleButtonStar1.setBorder(null);
        toggleButtonStar1.setBorderPainted(false);
        toggleButtonStar1.setContentAreaFilled(false);
        toggleButtonStar1.setFocusPainted(false);
        toggleButtonStar1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-christmas-star-24.png"))); // NOI18N
        toggleButtonStar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonStar1ActionPerformed(evt);
            }
        });

        toggleButtonStar2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-star-24.png"))); // NOI18N
        toggleButtonStar2.setBorder(null);
        toggleButtonStar2.setBorderPainted(false);
        toggleButtonStar2.setContentAreaFilled(false);
        toggleButtonStar2.setFocusPainted(false);
        toggleButtonStar2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-christmas-star-24.png"))); // NOI18N
        toggleButtonStar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonStar2ActionPerformed(evt);
            }
        });

        toggleButtonStar3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-star-24.png"))); // NOI18N
        toggleButtonStar3.setBorder(null);
        toggleButtonStar3.setBorderPainted(false);
        toggleButtonStar3.setContentAreaFilled(false);
        toggleButtonStar3.setFocusPainted(false);
        toggleButtonStar3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-christmas-star-24.png"))); // NOI18N
        toggleButtonStar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonStar3ActionPerformed(evt);
            }
        });

        toggleButtonStar4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-star-24.png"))); // NOI18N
        toggleButtonStar4.setBorder(null);
        toggleButtonStar4.setBorderPainted(false);
        toggleButtonStar4.setContentAreaFilled(false);
        toggleButtonStar4.setFocusPainted(false);
        toggleButtonStar4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-christmas-star-24.png"))); // NOI18N
        toggleButtonStar4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonStar4ActionPerformed(evt);
            }
        });

        toggleButtonStar5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-star-24.png"))); // NOI18N
        toggleButtonStar5.setBorder(null);
        toggleButtonStar5.setBorderPainted(false);
        toggleButtonStar5.setContentAreaFilled(false);
        toggleButtonStar5.setFocusPainted(false);
        toggleButtonStar5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-christmas-star-24.png"))); // NOI18N
        toggleButtonStar5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonStar5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBarra, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(labelCMS))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(33, 33, 33)
                                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(labelPaperTitle)
                                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                                .addComponent(fieldPaperTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(paperDownloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                                .addComponent(labelRating)
                                                                .addGap(8, 8, 8)
                                                                .addComponent(toggleButtonStar1)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(toggleButtonStar2)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(toggleButtonStar3)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(toggleButtonStar4)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(toggleButtonStar5))
                                                        .addComponent(labelReview)
                                                        .addComponent(labelPrivateComment)
                                                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addComponent(submitReviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addComponent(scrollPanelPrivateComment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                                                                        .addComponent(scrollPanelReview, javax.swing.GroupLayout.Alignment.LEADING))))))
                                .addContainerGap(49, Short.MAX_VALUE))
        );
        panelBackgroundLayout.setVerticalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addComponent(labelCMS)))
                                .addGap(18, 18, 18)
                                .addComponent(panelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelPaperTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(fieldPaperTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(paperDownloadButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(labelReview)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPanelReview, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(labelRating)
                                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(toggleButtonStar1)
                                                .addComponent(toggleButtonStar2)
                                                .addComponent(toggleButtonStar3)
                                                .addComponent(toggleButtonStar4)
                                                .addComponent(toggleButtonStar5)))
                                .addGap(31, 31, 31)
                                .addComponent(labelPrivateComment)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPanelPrivateComment, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                                .addComponent(submitReviewButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Return to home screen using the ReviewerConferenceControl
        if (reviewerConferenceControl != null) {
            // Close this view
            this.dispose();
            // Return to home
            reviewerConferenceControl.returnToHome();
        }
    }

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Go back to the previous screen
        if (reviewerConferenceControl != null) {
            // Close this view
            this.dispose();
            // Show the reviewer dashboard view
            if(!isSubReview)
                reviewerConferenceControl.showReviewerDashboardView();
            else
                reviewerConferenceControl.returnToReviewerView();
        }
    }

    private void submitReviewButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Check if all fields are filled
        // TODO: spostare nella control
        String reviewText = textAreaReview.getText().trim();
        String privateComment = textAreaPrivateComment.getText().trim();

        if (reviewText.isEmpty() || currentRating == 0) {
            // Show error popup if fields are not filled
            new ErrorPopupView("Errore: Compilare tutti i campi obbligatori.");
            return;
        }

        // Submit review with all parameters
        boolean success = reviewerConferenceControl.submitReview(AppSession.getInstance().getUserId(), paperId,
                reviewText, currentRating, privateComment, reviewId);

        if(success) {
            this.dispose();
        }
    }

    private void paperDownloadButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO: spostare nella control
        // Download the paper using the ReviewerConferenceControl
        if (reviewerConferenceControl != null) {
            boolean success = reviewerConferenceControl.downloadPaper(paperId, paperTitle);
            if (!success) {
                new ErrorPopupView("Errore nel download del file.");
            } else {
                SystemNotification.showNotification("Submeet Download", "Paper scaricato con successo");
            }
        }
    }


    private void toggleButtonStar1ActionPerformed(java.awt.event.ActionEvent evt) {
        // Set rating to 1 and update star selection
        currentRating = 1;
        updateStarSelection();
    }

    private void toggleButtonStar2ActionPerformed(java.awt.event.ActionEvent evt) {
        // Set rating to 2 and update star selection
        currentRating = 2;
        updateStarSelection();
    }

    private void toggleButtonStar3ActionPerformed(java.awt.event.ActionEvent evt) {
        // Set rating to 3 and update star selection
        currentRating = 3;
        updateStarSelection();
    }

    private void toggleButtonStar4ActionPerformed(java.awt.event.ActionEvent evt) {
        // Set rating to 4 and update star selection
        currentRating = 4;
        updateStarSelection();
    }

    private void toggleButtonStar5ActionPerformed(java.awt.event.ActionEvent evt) {
        // Set rating to 5 and update star selection
        currentRating = 5;
        updateStarSelection();
    }

    private void updateStarSelection() {
        // Update the selection state of all stars based on currentRating
        toggleButtonStar1.setSelected(currentRating >= 1);
        toggleButtonStar2.setSelected(currentRating >= 2);
        toggleButtonStar3.setSelected(currentRating >= 3);
        toggleButtonStar4.setSelected(currentRating >= 4);
        toggleButtonStar5.setSelected(currentRating >= 5);
    }


    // Variables declaration - do not modify
    private javax.swing.JButton backButton;
    private javax.swing.JTextField fieldPaperTitle;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel labelCMS;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelPaperTitle;
    private javax.swing.JLabel labelPrivateComment;
    private javax.swing.JLabel labelRating;
    private javax.swing.JLabel labelReview;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelBarra;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JButton paperDownloadButton;
    private javax.swing.JScrollPane scrollPanelPrivateComment;
    private javax.swing.JScrollPane scrollPanelReview;
    private javax.swing.JButton submitReviewButton;
    private javax.swing.JTextArea textAreaPrivateComment;
    private javax.swing.JTextArea textAreaReview;
    private javax.swing.JToggleButton toggleButtonStar1;
    private javax.swing.JToggleButton toggleButtonStar2;
    private javax.swing.JToggleButton toggleButtonStar3;
    private javax.swing.JToggleButton toggleButtonStar4;
    private javax.swing.JToggleButton toggleButtonStar5;
    // End of variables declaration
}
