package com.submeet.client.revisore.view;

import com.submeet.client.revisore.controller.ReviewerConferenceControl;

import javax.swing.*;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;

public class SubReviewerEmailView extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SubReviewerEmailView.class.getName());
    private List<Map<String, Object>> subReviewerList;
    private ReviewerConferenceControl control;
    private int paperId;
    private String paperTitle;

    /**
     * Creates new form SubReviewerEmailView
     */
    public SubReviewerEmailView(NewReviewView parent, List<Map<String, Object>> subReviewerList, ReviewerConferenceControl control, int paperId, String paperTitle) {
        super(parent, "Delega a sottorevisore", true);

        this.subReviewerList = subReviewerList;
        this.control = control;
        this.paperTitle = paperTitle;
        this.paperId = paperId;
        initComponents();
        setLocationRelativeTo(null);

        this.displaySubReviewerList();
        this.setVisible(true);
        setResizable(false);
    }

    public void displaySubReviewerList() {
        DefaultListModel<String> model = new DefaultListModel<>();
        model.clear();

        for (Map<String, Object> subReviewer : subReviewerList) {
            model.addElement(subReviewer.get("email").toString());
        }
        listUsers.setModel(model);
    }

    public LinkedList<Integer> getSelectedUsers() {
        LinkedList<Integer> selectedUsers = new LinkedList<>();
        int[] selectedIndices = listUsers.getSelectedIndices();

        for (int index : selectedIndices) {
            if (index >= 0 && index < subReviewerList.size()) {
                selectedUsers.add(Integer.parseInt(subReviewerList.get(index).get("userId").toString()));
            }
        }

        return selectedUsers;
    }

    public LinkedList<String> getSelectedUserEmails() {
        LinkedList<String> selectedEmails = new LinkedList<>();
        int[] selectedIndices = listUsers.getSelectedIndices();

        for (int index : selectedIndices) {
            if (index >= 0 && index < subReviewerList.size()) {
                selectedEmails.add(subReviewerList.get(index).get("email").toString());
            }
        }

        return selectedEmails;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelCMS = new javax.swing.JLabel();
        panelBarra = new javax.swing.JPanel();
        labelText = new javax.swing.JLabel();
        scrollPanelUtenti = new javax.swing.JScrollPane();
        listUsers = new javax.swing.JList<>();
        delegateButton = new javax.swing.JButton();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SubMeet_140x140.png"))); // NOI18N

        labelCMS.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelCMS.setForeground(new java.awt.Color(36, 105, 186));
        labelCMS.setText("CONFERENCE MANAGEMENT SYSTEM");

        panelBarra.setBackground(new java.awt.Color(204, 204, 204));
        panelBarra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBarra.setPreferredSize(new java.awt.Dimension(233, 23));

        javax.swing.GroupLayout panelBarraLayout = new javax.swing.GroupLayout(panelBarra);
        panelBarra.setLayout(panelBarraLayout);
        panelBarraLayout.setHorizontalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 466, Short.MAX_VALUE)
        );
        panelBarraLayout.setVerticalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 20, Short.MAX_VALUE)
        );

        labelText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelText.setText("SELEZIONA UNO O PIU UTENTI");

        scrollPanelUtenti.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scrollPanelUtenti.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listUsers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPanelUtenti.setViewportView(listUsers);

        delegateButton.setBackground(new java.awt.Color(153, 153, 255));
        delegateButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        delegateButton.setText("DELEGA REVISIONE");
        delegateButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        delegateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delegateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBarra, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelCMS)
                                .addGap(0, 0, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(delegateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(161, 161, 161))
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(50, 50, 50)
                                                .addComponent(scrollPanelUtenti, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(98, 98, 98)
                                                .addComponent(labelText)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBackgroundLayout.setVerticalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(10, 10, 10)
                                                .addComponent(labelCMS)))
                                .addGap(18, 18, 18)
                                .addComponent(panelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(labelText)
                                .addGap(18, 18, 18)
                                .addComponent(scrollPanelUtenti, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(delegateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void delegateButtonActionPerformed(java.awt.event.ActionEvent evt) {
        control.sendDelegationInvite(getSelectedUsers(), getSelectedUserEmails(), paperId, paperTitle);
        this.dispose();
    }

    // Variables declaration - do not modify
    private javax.swing.JButton delegateButton;
    private javax.swing.JLabel labelCMS;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelText;
    private javax.swing.JList<String> listUsers;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelBarra;
    private javax.swing.JScrollPane scrollPanelUtenti;
    // End of variables declaration
}

