package com.submeet.client.account.view;

import com.submeet.client.utility.AppSession;
import com.submeet.dbmsboundary.DBMSBoundary;

import java.awt.event.ActionListener;

/**
 *
 * @author aless
 */
public class HomeRouterView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HomeRouterView.class.getName());

    /**
     * Creates new form HomeView
     */
    public HomeRouterView() {
        initComponents();
        setLocationRelativeTo(null);
        setSize(470, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        sfondo = new javax.swing.JPanel();
        panelBarra = new javax.swing.JPanel();
        labelSchermata = new javax.swing.JLabel();
        reviewerButton = new javax.swing.JButton();
        chairButton = new javax.swing.JButton();
        labelStringa = new javax.swing.JLabel();
        authorButton = new javax.swing.JButton();
        editorButton = new javax.swing.JButton();
        profileButton = new javax.swing.JButton();
        notificButton = new javax.swing.JButton();
        labelLogo = new javax.swing.JLabel();
        labelCMS = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(450, 500));
        setResizable(false);

        sfondo.setBackground(new java.awt.Color(255, 255, 255));

        panelBarra.setBackground(new java.awt.Color(204, 204, 204));

        labelSchermata.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        labelSchermata.setText("Benvenuto " + DBMSBoundary.getUserInfo(AppSession.getInstance().getUserId()).getName());

        javax.swing.GroupLayout panelBarraLayout = new javax.swing.GroupLayout(panelBarra);
        panelBarra.setLayout(panelBarraLayout);
        panelBarraLayout.setHorizontalGroup(
            panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBarraLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(labelSchermata)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelBarraLayout.setVerticalGroup(
            panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBarraLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelSchermata))
        );

        reviewerButton.setBackground(new java.awt.Color(34, 94, 150));
        reviewerButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        reviewerButton.setText("REVISORE");

        chairButton.setBackground(new java.awt.Color(34, 94, 152));
        chairButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        chairButton.setText("CHAIR");

        labelStringa.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        labelStringa.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelStringa.setText("Accedi come...");

        authorButton.setBackground(new java.awt.Color(34, 94, 150));
        authorButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        authorButton.setText("AUTORE");

        editorButton.setBackground(new java.awt.Color(34, 94, 150));
        editorButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        editorButton.setText("EDITORE");

        profileButton.setBackground(new java.awt.Color(204, 204, 204));
        profileButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        profileButton.setText("PROFILO");

        notificButton.setBackground(new java.awt.Color(204, 204, 204));
        notificButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        notificButton.setText("NOTIFICHE");

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SubMeet_140x140.png"))); // NOI18N

        labelCMS.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelCMS.setForeground(new java.awt.Color(34, 94, 150));
        labelCMS.setText("CONFERENCE MANAGEMENT SYSTEM");

        javax.swing.GroupLayout sfondoLayout = new javax.swing.GroupLayout(sfondo);
        sfondo.setLayout(sfondoLayout);
        sfondoLayout.setHorizontalGroup(
            sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sfondoLayout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(authorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(reviewerButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editorButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
            .addComponent(panelBarra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sfondoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(profileButton)
                .addGap(3, 3, 3)
                .addComponent(notificButton)
                .addContainerGap())
            .addGroup(sfondoLayout.createSequentialGroup()
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sfondoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelLogo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelCMS))
                    .addGroup(sfondoLayout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(labelStringa, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        sfondoLayout.setVerticalGroup(
            sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sfondoLayout.createSequentialGroup()
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sfondoLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(sfondoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(labelCMS)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(profileButton)
                    .addComponent(notificButton))
                .addGap(28, 28, 28)
                .addComponent(labelStringa)
                .addGap(52, 52, 52)
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chairButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reviewerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(sfondoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(authorButton, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(109, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sfondo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }

    // Methods to set action listeners for buttons
    public void setChairButtonListener(ActionListener listener) {
        chairButton.addActionListener(listener);
    }

    public void setReviewerButtonListener(ActionListener listener) {
        reviewerButton.addActionListener(listener);
    }

    public void setAuthorButtonListener(ActionListener listener) {
        authorButton.addActionListener(listener);
    }

    public void setEditorButtonListener(ActionListener listener) {
        editorButton.addActionListener(listener);
    }

    public void setProfileButtonListener(ActionListener listener) {
        profileButton.addActionListener(listener);
    }

    public void setNotificButtonListener(ActionListener listener) {
        notificButton.addActionListener(listener);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton authorButton;
    private javax.swing.JButton chairButton;
    private javax.swing.JButton editorButton;
    private javax.swing.JLabel labelCMS;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelSchermata;
    private javax.swing.JLabel labelStringa;
    private javax.swing.JButton notificButton;
    private javax.swing.JPanel panelBarra;
    private javax.swing.JButton profileButton;
    private javax.swing.JButton reviewerButton;
    private javax.swing.JPanel sfondo;
    // End of variables declaration//GEN-END:variables
}
