/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.submeet.client.account.view;

import com.submeet.client.account.controller.AuthControl;
import com.submeet.client.account.controller.PasswordRecoveryControl;
import com.submeet.client.common.ErrorPopupView;

/**
 *
 * @author aless
 */
public class PasswordRecoveryView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PasswordRecoveryView.class.getName());
    private final PasswordRecoveryControl passwordRecoveryControl;

    /**
     * Creates new form RecoveryPasswordView
     */
    public PasswordRecoveryView(PasswordRecoveryControl passwordRecoveryControl) {
        this.passwordRecoveryControl = passwordRecoveryControl;
        initComponents();
        setLocationRelativeTo(null);
        setSize(370, 400);
        setupListeners();
    }

    private void setupListeners() {
        getPasswordButton.addActionListener(e -> confirmButtonAction());
        backButton.addActionListener(e -> {
            dispose();
            new LoginView(new AuthControl()).setVisible(true);
        });
    }

    private void confirmButtonAction() {
        String email = fieldEmail.getText().trim();

        // Check if email is empty
        if (email.isEmpty()) {
            new ErrorPopupView("Il campo email non può essere vuoto.");
            return;
        }

        // Check if email exists
        if (!passwordRecoveryControl.checkEmailExists(email)) {
            new ErrorPopupView("L'email inserita non è registrata nel sistema.");
            return;
        }

        // Email exists, recover password
        passwordRecoveryControl.sendPassword(email);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        lblLogo = new javax.swing.JLabel();
        labelTitle = new javax.swing.JLabel();
        labelSubtitle = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        getPasswordButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        lblLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SubMeet_140x140.png"))); // NOI18N

        labelTitle.setFont(new java.awt.Font("Artifakt Element Black", 1, 24)); // NOI18N
        labelTitle.setText("Recupera Password");

        labelSubtitle.setFont(new java.awt.Font("Artifakt Element Book", 0, 12)); // NOI18N
        labelSubtitle.setText("Inserisci l'email utilizzata per la registrazione");

        labelEmail.setFont(new java.awt.Font("Artifakt Element Black", 1, 11)); // NOI18N
        labelEmail.setText("Email");

        getPasswordButton.setBackground(new java.awt.Color(204, 255, 204));
        getPasswordButton.setText("RECUPERA PASSWORD");

        backButton.setText("INDIETRO");
        backButton.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addComponent(backButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(getPasswordButton))
                        .addComponent(labelSubtitle))
                .addGap(55, 55, 55))
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(labelEmail))
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(labelTitle))
                    .addGroup(panelBackgroundLayout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        panelBackgroundLayout.setVerticalGroup(
            panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBackgroundLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSubtitle)
                .addGap(28, 28, 28)
                .addComponent(labelEmail)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77)
                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backButton)
                    .addComponent(getPasswordButton))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JButton getPasswordButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelSubtitle;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JPanel panelBackground;
    // End of variables declaration//GEN-END:variables
}
