package com.submeet.client.account.view;

import com.submeet.client.account.controller.AuthControl;
import com.submeet.client.common.ErrorPopupView;
import com.submeet.dbmsboundary.DBMSBoundary;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

public class SignUpView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(SignUpView.class.getName());
    private AuthControl authControl;

    /**
     * Creates new form SignUpView
     */
    public SignUpView(AuthControl authControl) {
        this.authControl = authControl;
        initComponents();
        setLocationRelativeTo(null);
        populatePanelInterestAreas();

        setVisible(true);
    }

    public void populatePanelInterestAreas() {
        panelInterestAreas.setLayout(new BoxLayout(panelInterestAreas, BoxLayout.Y_AXIS));

        List<Map<Integer, String>> interestAreas = DBMSBoundary.getSpecializations();

        if (interestAreas != null) {
            for (Map<Integer, String> area : interestAreas) {
                for (Map.Entry<Integer, String> entry : area.entrySet()) {
                    int id = entry.getKey();
                    String name = entry.getValue();

                    // Create a checkbox with the specialization name
                    JCheckBox checkBox = new JCheckBox(name);
                    checkBox.setActionCommand(String.valueOf(id)); // store the ID for later retrieval

                    panelInterestAreas.add(checkBox); // Add to the panel
                }
            }

            // Refresh the panel to display the new checkboxes
            panelInterestAreas.revalidate();
            panelInterestAreas.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelSubTitle = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        fieldName = new javax.swing.JTextField();
        labelSurname = new javax.swing.JLabel();
        fieldSurname = new javax.swing.JTextField();
        labelEmail = new javax.swing.JLabel();
        fieldEmail = new javax.swing.JTextField();
        labelNazionality = new javax.swing.JLabel();
        scrollPanelNazionality = new javax.swing.JScrollPane();
        comboBoxNazionality = new javax.swing.JComboBox<>();
        labelPassword = new javax.swing.JLabel();
        labelConfirmPassword = new javax.swing.JLabel();
        fieldPassword = new javax.swing.JPasswordField();
        fieldConfirmPassword = new javax.swing.JPasswordField();
        signUpButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelInterestAreas = new javax.swing.JLabel();
        scrollPanelInterestAreas = new javax.swing.JScrollPane();
        panelInterestAreas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        labelTitle.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        labelTitle.setText("Benvenuto");

        labelSubTitle.setText("Compila i campi sottostanti per effettuare la registrazione");

        labelName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelName.setText("Nome");

        labelSurname.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelSurname.setText("Cognome");

        labelEmail.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelEmail.setText("Email");

        labelNazionality.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelNazionality.setText("Nazionalità");

        comboBoxNazionality.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Antigua e Barbuda", "Arabia Saudita", "Argentina", "Armenia", "Australia", "Austria", "Azerbaigian", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belgio", "Belize", "Benin", "Bhutan", "Bielorussia", "Birmania", "Bolivia", "Bosnia ed Erzegovina", "Botswana", "Brasile", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cambogia", "Camerun", "Canada", "Capo Verde", "Ciad", "Cile", "Cina", "Cipro", "Colombia", "Comore", "Congo", "Corea del Nord", "Corea del Sud", "Costa d'Avorio", "Costa Rica", "Croazia", "Cuba", "Danimarca", "Dominica", "Ecuador", "Egitto", "El Salvador", "Emirati Arabi Uniti", "Eritrea", "Estonia", "Eswatini", "Etiopia", "Fiji", "Filippine", "Finlandia", "Francia", "Gabon", "Gambia", "Georgia", "Germania", "Ghana", "Giamaica", "Giappone", "Gibuti", "Giordania", "Grecia", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guinea Equatoriale", "Guyana", "Haiti", "Honduras", "India", "Indonesia", "Iran", "Iraq", "Irlanda", "Islanda", "Israele", "Italia", "Kazakistan", "Kenya", "Kirghizistan", "Kiribati", "Kuwait", "Laos", "Lesotho", "Lettonia", "Libano", "Liberia", "Libia", "Liechtenstein", "Lituania", "Lussemburgo", "Macedonia del Nord", "Madagascar", "Malawi", "Malaysia", "Maldive", "Mali", "Malta", "Marocco", "Marshall", "Mauritania", "Mauritius", "Messico", "Micronesia", "Moldavia", "Monaco", "Mongolia", "Montenegro", "Mozambico", "Namibia", "Nauru", "Nepal", "Nicaragua", "Niger", "Nigeria", "Norvegia", "Nuova Zelanda", "Oman", "Paesi Bassi", "Pakistan", "Palau", "Palestina", "Panama", "Papua Nuova Guinea", "Paraguay", "Perù", "Polonia", "Portogallo", "Qatar", "Regno Unito", "Repubblica Centrafricana", "Repubblica Ceca", "Repubblica Democratica del Congo", "Repubblica Dominicana", "Romania", "Ruanda", "Russia", "Saint Kitts e Nevis", "Saint Lucia", "Saint Vincent e Grenadine", "Samoa", "San Marino", "Sao Tome e Principe", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovacchia", "Slovenia", "Somalia", "Spagna", "Sri Lanka", "Stati Uniti", "Sud Africa", "Sudan", "Sudan del Sud", "Suriname", "Svezia", "Svizzera", "Siria", "Tagikistan", "Tanzania", "Thailandia", "Timor Est", "Togo", "Tonga", "Trinidad e Tobago", "Tunisia", "Turchia", "Turkmenistan", "Tuvalu", "Ucraina", "Uganda", "Ungheria", "Uruguay", "Uzbekistan", "Vanuatu", "Vaticano", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe" }));
        scrollPanelNazionality.setViewportView(comboBoxNazionality);

        labelPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelPassword.setText("Password");

        labelConfirmPassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelConfirmPassword.setText("Conferma Password");

        signUpButton.setBackground(new java.awt.Color(153, 153, 255));
        signUpButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        signUpButton.setText("REGISTRATI");
        signUpButton.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        signUpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signUpButtonActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Hai già un account? Accedi qui");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        labelInterestAreas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInterestAreas.setText("Specializzazioni");

        javax.swing.GroupLayout panelInterestAreasLayout = new javax.swing.GroupLayout(panelInterestAreas);
        panelInterestAreas.setLayout(panelInterestAreasLayout);
        panelInterestAreasLayout.setHorizontalGroup(
                panelInterestAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 365, Short.MAX_VALUE)
        );
        panelInterestAreasLayout.setVerticalGroup(
                panelInterestAreasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 200, Short.MAX_VALUE)
        );

        scrollPanelInterestAreas.setViewportView(panelInterestAreas);

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelTitle)
                                .addGap(198, 198, 198))
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(94, 94, 94)
                                                .addComponent(labelSubTitle))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(fieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(labelConfirmPassword)
                                                        .addComponent(labelNazionality)
                                                        .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(labelName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(labelSurname)
                                                                        .addComponent(fieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addComponent(labelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                        .addComponent(labelInterestAreas)
                                                        .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                .addComponent(scrollPanelInterestAreas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                                                                .addComponent(scrollPanelNazionality, javax.swing.GroupLayout.Alignment.LEADING))
                                                        .addComponent(labelPassword)
                                                        .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(177, 177, 177)
                                                .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(163, 163, 163)
                                                .addComponent(jLabel1)))
                                .addContainerGap(60, Short.MAX_VALUE))
        );
        panelBackgroundLayout.setVerticalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(labelTitle)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSubTitle)
                                .addGap(27, 27, 27)
                                .addComponent(labelName)
                                .addGap(3, 3, 3)
                                .addComponent(fieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(labelSurname)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelNazionality)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPanelNazionality, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelInterestAreas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(scrollPanelInterestAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fieldConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(signUpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void signUpButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // Password regex
        String regexPassword = "^(?=.*[a-z])(?=.*[A-Z])(?=.*\\d)(?=.*[^a-zA-Z\\d]).{7,}$";
        String regexMail = "^[\\w.-]+@[\\w.-]+\\.[a-zA-Z]{2,}$";

        // Get user input
        String name = fieldName.getText();
        String surname = fieldSurname.getText();
        String email = fieldEmail.getText();
        String nationality = (String) comboBoxNazionality.getSelectedItem();
        String password = new String(fieldPassword.getPassword());
        String confirmPassword = new String(fieldConfirmPassword.getPassword());

        // Validate input fields
        if (name == null || name.isBlank()) {
            new ErrorPopupView("Nome non può essere vuoto.");
            return;
        }
        if (surname == null || surname.isBlank()) {
            new ErrorPopupView("Cognome non può essere vuoto.");
            return;
        }
        if (email == null || email.isBlank()) {
            new ErrorPopupView("Email non può essere vuota.");
            return;
        }
        if (nationality == null || nationality.isBlank()) {
            new ErrorPopupView("Nazionalità non può essere vuota.");
            return;
        }
        if (password.isBlank()) {
            new ErrorPopupView("Password non può essere vuota.");
            return;
        }
        if (confirmPassword.isBlank()) {
            new ErrorPopupView("Conferma password non può essere vuota.");
            return;
        }

        // Check if the email is valid
        if(!email.matches(regexMail)){
            new ErrorPopupView("Inserire un email valida.");
            return;
        }

        // Check if email already exists
        if(DBMSBoundary.checkEmailExists(email)) {
            new ErrorPopupView("L'email esiste già");
            return;
        }

        // Check password regex
        if (!password.matches(regexPassword)) {
            new ErrorPopupView("La password deve essere di 7 caratteri\navere un carattere maiuscolo, un carattere minuscolo, un numero e un carattere speciale.\n.");
            return;
        }

        // Check if passwords match
        if (!password.equals(confirmPassword)) {
            new ErrorPopupView("Le password non corrispondono.");
            return;
        }

        // Get selected specializations
        List<String> selectedSpecializations = new ArrayList<>();

        Component[] components = panelInterestAreas.getComponents();
        for (Component component : components) {
            if (component instanceof JCheckBox) {
                JCheckBox checkBox = (JCheckBox) component;
                if (checkBox.isSelected()) {
                    selectedSpecializations.add(checkBox.getActionCommand());
                }
            }
        }
        String[] specializations = selectedSpecializations.toArray(new String[0]);

        // Generate verification code and send email using AuthControl
        authControl.generateVerificationCode();
        authControl.sendVerificationEmail(name, email);

        // Show verification dialog
        authControl.showVerificationPopupView(email);

        if (authControl.isCodeVerified()) {
            // Verification successful, proceed with registration
            if (authControl.checkSignupCredentials(name, surname, email, nationality, password, confirmPassword, specializations)) {
                this.dispose();
            }
        }
    }

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {
        // Return to login view
        new com.submeet.client.account.view.LoginView(authControl);
        this.dispose();
    }

    // Variables declaration - do not modify
    private javax.swing.JComboBox<String> comboBoxNazionality;
    private javax.swing.JPasswordField fieldConfirmPassword;
    private javax.swing.JTextField fieldEmail;
    private javax.swing.JTextField fieldName;
    private javax.swing.JPasswordField fieldPassword;
    private javax.swing.JTextField fieldSurname;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelConfirmPassword;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelInterestAreas;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelNazionality;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JLabel labelSubTitle;
    private javax.swing.JLabel labelSurname;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelInterestAreas;
    private javax.swing.JScrollPane scrollPanelInterestAreas;
    private javax.swing.JScrollPane scrollPanelNazionality;
    private javax.swing.JButton signUpButton;
    // End of variables declaration
}
