package com.submeet.client.chair.view;

import com.submeet.client.chair.controller.CreateConferenceControl;
import com.submeet.dbmsboundary.DBMSBoundary;

import javax.swing.*;
import java.awt.*;
import java.util.List;
import java.util.Map;

public class ConferenceCreationView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ConferenceCreationView.class.getName());
    private CreateConferenceControl createConferenceControl;

    private javax.swing.JPanel panelInterestAreas;
    private javax.swing.JScrollPane scrollPanelInterestAreas;
    private javax.swing.JPanel panelLanguages;
    private javax.swing.JScrollPane scrollPanelLanguages;

    /**
     * Creates new form ConferenceCreationView
     */
    public ConferenceCreationView(CreateConferenceControl createConferenceControl) {
        this.createConferenceControl = createConferenceControl;
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        populatePanelInterestAreas();
        populatePanelLanguages();
    }

    public void populatePanelInterestAreas() {
        panelInterestAreas.setLayout(new BoxLayout(panelInterestAreas, BoxLayout.Y_AXIS));

        List<Map<Integer, String>> interestAreas = DBMSBoundary.getSpecializations();

        if (interestAreas != null) {
            for (Map<Integer, String> area : interestAreas) {
                for (Map.Entry<Integer, String> entry : area.entrySet()) {
                    int id = entry.getKey();
                    String name = entry.getValue();

                    // Create a checkbox with the specialization name
                    JCheckBox checkBox = new JCheckBox(name);
                    checkBox.setActionCommand(String.valueOf(id)); // store the ID for later retrieval

                    panelInterestAreas.add(checkBox); // Add to the panel
                }
            }

            // Refresh the panel to display the new checkboxes
            panelInterestAreas.revalidate();
            panelInterestAreas.repaint();
        }
    }

    public void populatePanelLanguages() {
        panelLanguages.setLayout(new BoxLayout(panelLanguages, BoxLayout.Y_AXIS));

        List<Map<Integer, String>> languages = DBMSBoundary.getLanguages();

        if (languages != null) {
            for (Map<Integer, String> lang : languages) {
                for (Map.Entry<Integer, String> entry : lang.entrySet()) {
                    int id = entry.getKey();
                    String name = entry.getValue();

                    // Create a checkbox with the language name
                    JCheckBox checkBox = new JCheckBox(name);
                    checkBox.setActionCommand(String.valueOf(id)); // store the ID for later retrieval

                    panelLanguages.add(checkBox); // Add to the panel
                }
            }

            // Refresh the panel to display the new checkboxes
            panelLanguages.revalidate();
            panelLanguages.repaint();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        labelLogo = new javax.swing.JLabel();
        labelCMS = new javax.swing.JLabel();
        panelBarra = new javax.swing.JPanel();
        homeButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        panelTitle = new javax.swing.JPanel();
        labelTitle = new javax.swing.JLabel();
        labelConferenceName = new javax.swing.JLabel();
        fieldConferenceName = new javax.swing.JTextField();
        labelInterestAreas = new javax.swing.JLabel();
        fieldInterestAreas = new javax.swing.JTextField();
        labelConferenceDate = new javax.swing.JLabel();
        labelSubmissionExpirationDate = new javax.swing.JLabel();
        labelReviewExpirationDate = new javax.swing.JLabel();
        labelFinalVersionExpirationDate = new javax.swing.JLabel();
        labelLanguages = new javax.swing.JLabel();
        fieldLanguages = new javax.swing.JTextField();
        labelMaxReviewer = new javax.swing.JLabel();
        spinnerMaxReviewer = new javax.swing.JSpinner();
        spinnerSubmissionExpirationDate = new javax.swing.JSpinner();
        buttonCreateConference = new javax.swing.JButton();
        spinnerReviewExpirationDate = new javax.swing.JSpinner();
        spinnerFinalVersionExpirationDate = new javax.swing.JSpinner();
        spinnerDate = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        labelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SubMeet_140x140.png"))); // NOI18N

        labelCMS.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        labelCMS.setForeground(new java.awt.Color(36, 105, 186));
        labelCMS.setText("CONFERENCE MANAGEMENT SYSTEM");

        panelBarra.setBackground(new java.awt.Color(204, 204, 204));
        panelBarra.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelBarra.setPreferredSize(new java.awt.Dimension(233, 23));

        homeButton.setBackground(new java.awt.Color(204, 204, 204));
        homeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-home-16.png"))); // NOI18N
        homeButton.setBorder(null);
        homeButton.setBorderPainted(false);
        homeButton.setContentAreaFilled(false);
        homeButton.setPreferredSize(new java.awt.Dimension(20, 20));
        homeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeButtonActionPerformed(evt);
            }
        });

        backButton.setBackground(new java.awt.Color(204, 204, 204));
        backButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-back-20.png"))); // NOI18N
        backButton.setBorder(null);
        backButton.setBorderPainted(false);
        backButton.setContentAreaFilled(false);
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        panelTitle.setBackground(new java.awt.Color(153, 153, 255));
        panelTitle.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        labelTitle.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        labelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitle.setText("CREA CONFERENZA");

        javax.swing.GroupLayout panelTitleLayout = new javax.swing.GroupLayout(panelTitle);
        panelTitle.setLayout(panelTitleLayout);
        panelTitleLayout.setHorizontalGroup(
                panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelTitleLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(labelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                .addContainerGap())
        );
        panelTitleLayout.setVerticalGroup(
                panelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTitleLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(labelTitle))
        );

        javax.swing.GroupLayout panelBarraLayout = new javax.swing.GroupLayout(panelBarra);
        panelBarra.setLayout(panelBarraLayout);
        panelBarraLayout.setHorizontalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBarraLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(panelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(backButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
        );
        panelBarraLayout.setVerticalGroup(
                panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(panelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelBarraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(backButton)
                                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        labelConferenceName.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelConferenceName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConferenceName.setText("Nome Conferenza");

        fieldConferenceName.setMaximumSize(new java.awt.Dimension(64, 22));
        fieldConferenceName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldConferenceNameActionPerformed(evt);
            }
        });

        labelInterestAreas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelInterestAreas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelInterestAreas.setText("Aree Specialistiche");

        panelInterestAreas = new javax.swing.JPanel();
        scrollPanelInterestAreas = new javax.swing.JScrollPane(panelInterestAreas);
        scrollPanelInterestAreas.setPreferredSize(new java.awt.Dimension(388, 100));

        labelConferenceDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelConferenceDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelConferenceDate.setText("Data Conferenza");

        labelSubmissionExpirationDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelSubmissionExpirationDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelSubmissionExpirationDate.setText("Data Scadenza Sottomissioni");

        labelReviewExpirationDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelReviewExpirationDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelReviewExpirationDate.setText("Data Scadenza Revisioni");

        labelFinalVersionExpirationDate.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelFinalVersionExpirationDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelFinalVersionExpirationDate.setText("Data Scadenza Sottomissioni Versioni Finali");

        labelLanguages.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelLanguages.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelLanguages.setText("Lingue");

        panelLanguages = new javax.swing.JPanel();
        scrollPanelLanguages = new javax.swing.JScrollPane(panelLanguages);
        scrollPanelLanguages.setPreferredSize(new java.awt.Dimension(388, 100));

        labelMaxReviewer.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelMaxReviewer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMaxReviewer.setText("N° Revisori Per Articolo (MAX)");

        spinnerMaxReviewer.setModel(new javax.swing.SpinnerNumberModel(2, 2, 5, 1));

        spinnerSubmissionExpirationDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_YEAR));

        buttonCreateConference.setBackground(new java.awt.Color(153, 153, 255));
        buttonCreateConference.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonCreateConference.setText("CREA CONFERENZA");
        buttonCreateConference.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonCreateConference.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCreateConferenceActionPerformed(evt);
            }
        });

        spinnerReviewExpirationDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_YEAR));

        spinnerFinalVersionExpirationDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_YEAR));

        spinnerDate.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), new java.util.Date(), null, java.util.Calendar.DAY_OF_YEAR));

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBarra, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(20, 20, 20)
                                                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(labelCMS))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(28, 28, 28)
                                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(labelConferenceName)
                                                        .addComponent(fieldConferenceName, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(labelInterestAreas)
                                                        .addComponent(scrollPanelInterestAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(labelConferenceDate)
                                                        .addComponent(labelSubmissionExpirationDate)
                                                        .addComponent(labelReviewExpirationDate)
                                                        .addComponent(labelFinalVersionExpirationDate)
                                                        .addComponent(labelLanguages)
                                                        .addComponent(scrollPanelLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(labelMaxReviewer)
                                                        .addComponent(spinnerMaxReviewer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(spinnerSubmissionExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(spinnerReviewExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(spinnerFinalVersionExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(spinnerDate, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(35, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelBackgroundLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(buttonCreateConference)
                                .addGap(164, 164, 164))
        );
        panelBackgroundLayout.setVerticalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(25, 25, 25)
                                                .addComponent(labelCMS))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(15, 15, 15)
                                                .addComponent(labelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(panelBarra, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(labelConferenceName)
                                .addGap(2, 2, 2)
                                .addComponent(fieldConferenceName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelInterestAreas)
                                .addGap(2, 2, 2)
                                .addComponent(scrollPanelInterestAreas, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelConferenceDate)
                                .addGap(2, 2, 2)
                                .addComponent(spinnerDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelSubmissionExpirationDate)
                                .addGap(2, 2, 2)
                                .addComponent(spinnerSubmissionExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelReviewExpirationDate)
                                .addGap(2, 2, 2)
                                .addComponent(spinnerReviewExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelFinalVersionExpirationDate)
                                .addGap(2, 2, 2)
                                .addComponent(spinnerFinalVersionExpirationDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelLanguages)
                                .addGap(2, 2, 2)
                                .addComponent(scrollPanelLanguages, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelMaxReviewer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(spinnerMaxReviewer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonCreateConference, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(29, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void homeButtonActionPerformed(java.awt.event.ActionEvent evt) {
        createConferenceControl.returnToHome();
    }

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {
        createConferenceControl.goBack();
    }

    private void fieldConferenceNameActionPerformed(java.awt.event.ActionEvent evt) {
        // Auto-generated method
    }

    private void buttonCreateConferenceActionPerformed(java.awt.event.ActionEvent evt) {
        createConferenceControl.createConference(this.getConferenceName(), this.getInterestAreas(), this.getLanguages(), this.getMaxReviewers(), this.getSubmissionExpirationDate(), this.getReviewExpirationDate(), this.getFinalVersionExpirationDate(), this.getConferenceDate());
    }

    // Getter methods for form fields
    public String getConferenceName() {
        return fieldConferenceName.getText();
    }

    public String getInterestAreas() {
        StringBuilder specializationsBuilder = new StringBuilder();
        Component[] components = panelInterestAreas.getComponents();
        for (Component component : components) {
            if (component instanceof JCheckBox) {
                JCheckBox checkBox = (JCheckBox) component;
                if (checkBox.isSelected()) {
                    if (specializationsBuilder.length() > 0) {
                        specializationsBuilder.append(";");
                    }
                    specializationsBuilder.append(checkBox.getActionCommand()); // This contains the specializationId
                }
            }
        }
        return specializationsBuilder.toString();
    }

    public java.util.Date getConferenceDate() {
        return (java.util.Date) spinnerDate.getValue();
    }

    public java.util.Date getSubmissionExpirationDate() {
        return (java.util.Date) spinnerSubmissionExpirationDate.getValue();
    }

    public java.util.Date getReviewExpirationDate() {
        return (java.util.Date) spinnerReviewExpirationDate.getValue();
    }

    public java.util.Date getFinalVersionExpirationDate() {
        return (java.util.Date) spinnerFinalVersionExpirationDate.getValue();
    }

    public String getLanguages() {
        StringBuilder languagesBuilder = new StringBuilder();
        Component[] components = panelLanguages.getComponents();
        for (Component component : components) {
            if (component instanceof JCheckBox) {
                JCheckBox checkBox = (JCheckBox) component;
                if (checkBox.isSelected()) {
                    if (languagesBuilder.length() > 0) {
                        languagesBuilder.append(";");
                    }
                    languagesBuilder.append(checkBox.getActionCommand()); // This contains the languageId
                }
            }
        }
        return languagesBuilder.toString();
    }

    public int getMaxReviewers() {
        return (Integer) spinnerMaxReviewer.getValue();
    }

    public void setCreateConferenceButtonListener(java.awt.event.ActionListener listener) {
        buttonCreateConference.addActionListener(listener);
    }


    // Variables declaration - do not modify
    private javax.swing.JButton backButton;
    private javax.swing.JButton buttonCreateConference;
    private javax.swing.JTextField fieldConferenceName;
    private javax.swing.JTextField fieldInterestAreas;
    private javax.swing.JTextField fieldLanguages;
    private javax.swing.JButton homeButton;
    private javax.swing.JLabel labelCMS;
    private javax.swing.JLabel labelConferenceDate;
    private javax.swing.JLabel labelConferenceName;
    private javax.swing.JLabel labelFinalVersionExpirationDate;
    private javax.swing.JLabel labelInterestAreas;
    private javax.swing.JLabel labelLanguages;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelMaxReviewer;
    private javax.swing.JLabel labelReviewExpirationDate;
    private javax.swing.JLabel labelSubmissionExpirationDate;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JPanel panelBarra;
    private javax.swing.JPanel panelTitle;
    private javax.swing.JSpinner spinnerDate;
    private javax.swing.JSpinner spinnerFinalVersionExpirationDate;
    private javax.swing.JSpinner spinnerMaxReviewer;
    private javax.swing.JSpinner spinnerReviewExpirationDate;
    private javax.swing.JSpinner spinnerSubmissionExpirationDate;
    // End of variables declaration
}
