package com.submeet.client.chair.view;

import com.submeet.client.chair.controller.ConferenceDashboardControl;
import com.submeet.client.common.ErrorPopupView;
import com.submeet.client.common.SuccessPopupView;
import com.submeet.client.entity.EntityUser;
import java.util.ArrayList;
import javax.swing.*;

public class ManualPaperAssignmentView extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ManualPaperAssignmentView.class.getName());
    private ConferenceDashboardControl control;
    private ArrayList<EntityUser> reviewers;
    private int paperId;

    /**
     * Creates new form ManualAssignationView
     */
    public ManualPaperAssignmentView() {
        initComponents();
        setResizable(false);
    }

    /**
     * Creates new form ManualAssignationView with controller and reviewers list
     * @param control The controller
     * @param reviewers The list of reviewers
     * @param paperId The paper ID
     */
    public ManualPaperAssignmentView(ConferenceDashboardControl control, ArrayList<EntityUser> reviewers, int paperId) {
        initComponents();
        setLocationRelativeTo(null);
        this.control = control;
        this.reviewers = reviewers;
        this.paperId = paperId;

        // Set up the list model with reviewers
        DefaultListModel<String> listModel = new DefaultListModel<>();
        for (EntityUser reviewer : reviewers) {
            listModel.addElement(reviewer.getName() + " " + reviewer.getSurname() + " (" + reviewer.getEmail() + ")");
        }
        listUsers.setModel(listModel);

        // Enable multiple selection
        listUsers.setSelectionMode(javax.swing.ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);

        // Set modal behavior
        setModal(true);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        buttonAssign = new javax.swing.JButton();
        labelText = new javax.swing.JLabel();
        scrollPanelUsers = new javax.swing.JScrollPane();
        listUsers = new javax.swing.JList<>();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        buttonAssign.setBackground(new java.awt.Color(153, 153, 255));
        buttonAssign.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonAssign.setText("ASSEGNA");
        buttonAssign.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAssignActionPerformed(evt);
            }
        });

        labelText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelText.setText("SELEZIONA UNO O PIU UTENTI");

        scrollPanelUsers.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        scrollPanelUsers.setViewportBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listUsers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = {};
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        scrollPanelUsers.setViewportView(listUsers);

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addComponent(scrollPanelUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(126, 126, 126)
                                                .addComponent(labelText))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(188, 188, 188)
                                                .addComponent(buttonAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(80, Short.MAX_VALUE))
        );
        panelBackgroundLayout.setVerticalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(labelText)
                                .addGap(18, 18, 18)
                                .addComponent(scrollPanelUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addComponent(buttonAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void buttonAssignActionPerformed(java.awt.event.ActionEvent evt) {
        // Get selected indices
        int[] selectedIndices = listUsers.getSelectedIndices();

        // Create a list of selected reviewer IDs
        java.util.LinkedList<Integer> selectedReviewerIds = new java.util.LinkedList<>();
        for (int index : selectedIndices) {
            selectedReviewerIds.add(reviewers.get(index).getUserId());
        }

        // Call the controller method to assign reviewers
        if (control != null && !selectedReviewerIds.isEmpty()) {
            if(control.assignReviewersToPaper(paperId, selectedReviewerIds)) {
                new SuccessPopupView("Assegnazione riuscita.");
                this.dispose();
            } else {
                new ErrorPopupView("Assegnazione non riuscita.");
            }
        }
    }

    // Variables declaration - do not modify
    private javax.swing.JButton buttonAssign;
    private javax.swing.JLabel labelText;
    private javax.swing.JList<String> listUsers;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JScrollPane scrollPanelUsers;
    // End of variables declaration
}
