package com.submeet.client.chair.view;

import com.submeet.client.chair.controller.ConferenceDashboardControl;
import com.submeet.client.common.ErrorPopupView;

import javax.swing.*;

public class PaperAssignmentView extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PaperAssignmentView.class.getName());
    private ConferenceDashboardControl control;

    public PaperAssignmentView(java.awt.Frame parent, ConferenceDashboardControl control) {
        super(parent, "Assegnazione Paper", true); // true = modal
        this.control = control;

        initComponents();
        setLocationRelativeTo(parent); // Centra rispetto al parent
        setVisible(true); // Mostra il dialog
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        panelBackground = new javax.swing.JPanel();
        buttonAssign = new javax.swing.JButton();
        scrollPanelMethod = new javax.swing.JScrollPane();
        listMethod = new javax.swing.JList<>();
        labelText = new javax.swing.JLabel();

        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        panelBackground.setBackground(new java.awt.Color(255, 255, 255));

        buttonAssign.setBackground(new java.awt.Color(153, 153, 255));
        buttonAssign.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        buttonAssign.setText("ASSEGNA");
        buttonAssign.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        buttonAssign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAssignActionPerformed(evt);
            }
        });

        listMethod.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        listMethod.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "MECCANISMO DI OFFERTA", "ASSEGNAZIONE PER COMPETENZE", "ASSEGNAZIONE PER PAROLA CHIAVE" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        listMethod.setSelectionBackground(new java.awt.Color(153, 153, 255));
        scrollPanelMethod.setViewportView(listMethod);

        labelText.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelText.setText("SELEZIONA UN METODO PER L'ASSEGNAZIONE");

        javax.swing.GroupLayout panelBackgroundLayout = new javax.swing.GroupLayout(panelBackground);
        panelBackground.setLayout(panelBackgroundLayout);
        panelBackgroundLayout.setHorizontalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGroup(panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(labelText))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(101, 101, 101)
                                                .addComponent(scrollPanelMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                                .addGap(176, 176, 176)
                                                .addComponent(buttonAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(67, Short.MAX_VALUE))
        );
        panelBackgroundLayout.setVerticalGroup(
                panelBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panelBackgroundLayout.createSequentialGroup()
                                .addGap(28, 28, 28)
                                .addComponent(labelText)
                                .addGap(29, 29, 29)
                                .addComponent(scrollPanelMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                                .addComponent(buttonAssign, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(panelBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 20, Short.MAX_VALUE)
                                .addComponent(panelBackground, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>

    private void buttonAssignActionPerformed(java.awt.event.ActionEvent evt) {
        String selectedMethod = listMethod.getSelectedValue();
        if (selectedMethod != null) {
            control.assignPaper(selectedMethod);
            dispose();
        } else {
            new ErrorPopupView("Seleziona un metodo per l'assegnazione.");
        }
    }


    // Variables declaration - do not modify
    private javax.swing.JButton buttonAssign;
    private javax.swing.JLabel labelText;
    private javax.swing.JList<String> listMethod;
    private javax.swing.JPanel panelBackground;
    private javax.swing.JScrollPane scrollPanelMethod;
    // End of variables declaration
}

